---
title: Why Choose Sides? The Power of R and Python
author: Kirsten Hilling
date: '2021-05-06'
slug: welcome-to-kirsten-hilling-s-website
categories: []
tags: []
description: ''
---
There seems to be a constant battle of "R" people and "Python" people. Which is better? What is more practical? Which is cooler? To be honest, they're both great, but in their own ways. And at the end of the day, just knowing one will severely close you off from the pros of both. R has many pre-installed packages that let users do an endless amount of actions. From data visualization, generating statstics, and much more, using R's packages makes things a lot more simplified. While Python doesn't have this strength, using R with python can combine Python's strengths, including being fast to learn on and more readily available to users who want to learn how to code, with R's ease of creating awesome outputs. 

The way I do this is by using R's "Reticulate" package! Let's say you want to print out some sentences on your python code, but want to use a piece from R. To do this, you must combine both R and Python. See below for how we can do this by first using R, then Python, then calling in Python through R. 

```{R}
library(reticulate)
welcome<-"Welcome to My Website!"
```

```{python}
welcome="I'm glad you're here to see my R and Python skills."
print(r.welcome,welcome) #access R-defined objects with r. 
```

```{R}
cat(c(welcome,py$welcome)) #access Python-defined objects with py$
```

Now we're done! The Reticulate package is a great and efficient way to combine the two.

[Link to project 1](/project/project1/)

[Link to google](https://www.google.com)