<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Kirsten Hilling" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="the-dataset-i-am-using-in-this-project-pertains-to-various-social-factors-and-health-insurance-charges.-specifically-it-looks-at-age-sex-bmi-number-of-children-whether-or-not-they-are-a-smoker-region-they-live-in-the-us-and-their-yearly-charges-through-health-insurance.-there-are-7-variables-total-and-1338-observations.-i-am-interested-to-see-whether-or-not-there-is-an-interaction-between-all-of-these-factors-and-how-much-individuals-pay-for-their-health-insurance-charges.-this-is-an-increasingly-relevant-and-important-subject-to-look-at-especially-in-light-of-covid-19-showcasing-the-health-disparities-within-the-united-states." class="section level2">
<h2>The dataset I am using in this project pertains to various social factors and health insurance charges. Specifically, it looks at age, sex, bmi, number of children, whether or not they are a smoker, region they live in the US, and their yearly charges through health insurance. There are 7 variables total and 1338 observations. I am interested to see whether or not there is an interaction between all of these factors and how much individuals pay for their health insurance charges. This is an increasingly relevant and important subject to look at, especially in light of COVID-19 showcasing the health disparities within the United States.</h2>
<pre class="r"><code>library(tidyverse)
insurance &lt;- read.csv(&quot;~/insurance.csv&quot;)
man1 &lt;- manova(cbind(age, bmi, charges)~sex, data=insurance)

summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## sex 1 0.0063033 2.8207 3 1334 0.03777 *
## Residuals 1336
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>## Response age :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## sex 1 115 114.80 0.5814 0.4459
## Residuals 1336 263811 197.46
##
## Response bmi :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## sex 1 107 106.913 2.879 0.08998 .
## Residuals 1336 49613 37.136
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response charges :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## sex 1 6.4359e+08 643590180 4.3997 0.03613 *
## Residuals 1336 1.9543e+11 146280413
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>insurance%&gt;%group_by(sex)%&gt;%summarize(mean(age),mean(bmi), mean(charges))</code></pre>
<pre><code>## # A tibble: 2 x 4
##   sex    `mean(age)` `mean(bmi)` `mean(charges)`
##   &lt;fct&gt;        &lt;dbl&gt;       &lt;dbl&gt;           &lt;dbl&gt;
## 1 female        39.5        30.4          12570.
## 2 male          38.9        30.9          13957.</code></pre>
<pre class="r"><code>pairwise.t.test(insurance$age,insurance$sex, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  insurance$age and insurance$sex 
## 
##      female
## male 0.45  
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(insurance$bmi,insurance$sex, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  insurance$bmi and insurance$sex 
## 
##      female
## male 0.09  
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(insurance$charges,insurance$sex, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  insurance$charges and insurance$sex 
## 
##      female
## male 0.036 
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>.05/9</code></pre>
<pre><code>## [1] 0.005555556</code></pre>
</div>
<div id="when-running-the-manova-test-we-get-a-significant-result-meaning-at-least-one-of-the-variables-is-different-from-the-others.-when-performing-the-univariate-anova-test-there-is-not-a-significant-difference-between-male-and-female-when-looking-at-age-but-there-seems-to-be-a-significant-difference-between-male-and-female-in-both-bmi-and-charges.-next-post-hoc-t-tests-looked-further-at-the-groups.-overall-1-manova-test-3-univariate-anovas-and-9-t-tests-have-been-done-12-in-total.-the-original-unadjusted-probability-of-a-type-i-error-is-.05-but-adjusted-is-.0056.-before-the-adjustment-age-had-no-significant-difference-but-bmi-and-charges-did-have-significant-differences-between-male-and-female.-manova-tests-have-a-lot-of-assumptions.-it-assumes-that-all-the-variables-come-from-random-samples-and-their-own-observations.-it-also-assumes-that-the-variables-have-multivariate-normality-and-that-there-is-equal-variance-for-each-dv.-finally-the-test-assumes-that-there-arent-outliers-involved.-it-is-likely-that-the-variables-are-random-samplesand-that-there-is-normality-as-this-data-has-a-relatively-large-sample-size.-not-all-the-assumptions-are-met-since-this-is-common-for-manova-tests.-most-likely-the-assumption-that-there-are-no-outliers-is-probably-not-met." class="section level2">
<h2>When running the MANOVA test, we get a significant result, meaning at least one of the variables is different from the others. When performing the univariate Anova test, there is not a significant difference between male and female when looking at age, but there seems to be a significant difference between male and female in both BMI and charges. Next, post-hoc t tests looked further at the groups. Overall, 1 MANOVA test, 3 univariate ANOVAs, and 9 T-tests have been done (12 in total). The original unadjusted probability of a Type I error is .05, but adjusted is .0056. Before the adjustment, age had no significant difference, but BMI and charges did have significant differences between male and female. MANOVA tests have a lot of assumptions. It assumes that all the variables come from random samples and their own observations. It also assumes that the variables have multivariate normality and that there is equal variance for each DV. Finally, the test assumes that there aren’t outliers involved. It is likely that the variables are random samplesand that there is normality, as this data has a relatively large sample size. Not all the assumptions are met, since this is common for MANOVA tests. Most likely, the assumption that there are no outliers is probably not met.</h2>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1    23616.</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-2-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre><code>## [1] 0</code></pre>
<pre><code>##
## Welch Two Sample t-test
##
## data: charges by smoker
## t = -32.752, df = 311.85, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not
equal to 0
## 95 percent confidence interval:
## -25034.71 -22197.21
## sample estimates:
## mean in group no mean in group yes
## 8434.268 32050.232</code></pre>
</div>
<div id="in-this-test-the-hypothesis-is-that-there-is-a-difference-in-insurance-chargers-between-smokers-and-non-smokers.-the-null-hypothesis-is-that-there-is-no-difference-in-insurance-charges-between-smokers-and-non-smokers.-a-mean-difference-statistic-was-used-to-run-the-randomization-test.-in-the-actual-dataset-the-mean-difference-was-23615.96.-the-mean-of-the-randomly-distributed-set-was-0.-since-this-is-so-low-we-can-reject-the-null-hypothesis-and-say-there-is-a-difference-in-charges-between-those-who-smoke-and-those-who-do-not.-the-p-value-is-also-significant-in-the-t-test-done-with-the-actual-data." class="section level2">
<h2>In this test, the hypothesis is that there is a difference in insurance chargers between smokers and non-smokers. The null hypothesis is that there is no difference in insurance charges between smokers and non-smokers. A mean difference statistic was used to run the randomization test. In the actual dataset, the mean difference was 23,615.96. The mean of the randomly distributed set was 0. Since this is so low, we can reject the null hypothesis and say there is a difference in charges between those who smoke and those who do not. The p-value is also significant in the t-test done with the actual data.</h2>
<pre class="r"><code>library(sandwich)
library(lmtest)
insurance$bmi_c &lt;- insurance$bmi - mean(insurance$bmi)
summary(lm(charges~smoker*bmi_c,data=insurance))</code></pre>
<pre><code>##
## Call:
## lm(formula = charges ~ smoker * bmi_c, data = insurance)
##
## Residuals:
## Min 1Q Median 3Q Max
## -19768.0 -4400.7 -869.5 2957.7 31055.9
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 8435.24 188.87 44.661 &lt; 2e-16 ***
## smokeryes 23548.63 417.37 56.421 &lt; 2e-16 ***
## bmi_c 83.35 31.27 2.666 0.00778 **
## smokeryes:bmi_c 1389.76 66.78 20.810 &lt; 2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 6161 on 1334 degrees of freedom
## Multiple R-squared: 0.7418, Adjusted R-squared: 0.7412
## F-statistic: 1277 on 3 and 1334 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>insurance %&gt;% select(charges, smoker, bmi_c) %&gt;% na.omit %&gt;% ggplot(aes(charges, bmi_c, color=smoker)) + 
geom_point()+geom_smooth(method=&quot;lm&quot;) + geom_vline(xintercept=mean(insurance$charges,na.rm=T),lty=2)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>fit1&lt;-lm(charges~smoker*bmi_c,data=insurance)

resids&lt;-fit1$residuals
fitvals&lt;-fit1$fitted.values
plot(fitvals,resids); abline(h=0, col=&#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>par(mfrow=c(1,2)); hist(resids); qqnorm(resids); qqline(resids, col=&#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>summary(fit1)</code></pre>
<pre><code>##
## Call:
## lm(formula = charges ~ smoker * bmi_c, data = insurance)
##
## Residuals:
## Min 1Q Median 3Q Max
## -19768.0 -4400.7 -869.5 2957.7 31055.9
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 8435.24 188.87 44.661 &lt; 2e-16 ***
## smokeryes 23548.63 417.37 56.421 &lt; 2e-16 ***
## bmi_c 83.35 31.27 2.666 0.00778 **
## smokeryes:bmi_c 1389.76 66.78 20.810 &lt; 2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 6161 on 1334 degrees of freedom
## Multiple R-squared: 0.7418, Adjusted R-squared: 0.7412
## F-statistic: 1277 on 3 and 1334 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>coeftest(fit1, vcov=vcovHC(fit1)) </code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 8435.235 183.360 46.0037 &lt; 2.2e-16 ***
## smokeryes 23548.630 453.102 51.9721 &lt; 2.2e-16 ***
## bmi_c 83.351 28.610 2.9134 0.003635 **
## smokeryes:bmi_c 1389.756 78.604 17.6806 &lt; 2.2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
</div>
<div id="the-intercept-here-means-that-the-charges-for-the-average-non-smoker-is-now-8435.24.-the-smoker---yes-coefficient-means-that-people-who-are-smokers-have-predicted-charges-that-are-now-23548.63-higher-than-the-average-non-smoker.-the-bmi-centered-coefficient-means-that-for-every-one-unit-increase-in-bmi-there-is-an-83.35-increase-in-charges.-finally-for-smokeryesbmi_c-the-slope-of-bmi-on-charges-for-smokers-is-now-1389.76-greater-than-average.-the-model-explains-.74-of-the-variation.-when-checking-for-assumptions-the-data-is-relatively-linear.-it-is-not-completely-linear-nor-is-it-completely-normal.-it-is-decently-normal-though-and-doesnt-look-too-far-off.-when-using-the-coeftest-all-four-interactions-are-significant-as-they-were-originally.-there-is-a-significant-interaction-between-charges-bmi-and-whether-or-not-someone-was-a-smoker." class="section level2">
<h2>The intercept here means that the charges for the average non-smoker is now $8435.24. The smoker - yes coefficient means that people who are smokers have predicted charges that are now $23,548.63 higher than the average non-smoker. The bmi (centered) coefficient means that for every one unit increase in BMI, there is an $83.35 increase in charges. Finally, for smokeryes:bmi_c, the slope of bmi on charges for smokers is now $1,389.76 greater than average. The model explains .74 of the variation. When checking for assumptions, the data is relatively linear. It is not completely linear, nor is it completely normal. It is decently normal, though and doesn’t look too far off. When using the coeftest, all four interactions are significant, as they were originally. There is a significant interaction between charges, bmi, and whether or not someone was a smoker.</h2>
<pre class="r"><code> fit&lt;-lm(charges ~ smoker * bmi_c, data=insurance)
  resids&lt;-fit$residuals
  fitted&lt;-fit$fitted.values
  
  resid_resamp&lt;-replicate(5000,{
    new_resids&lt;-sample(resids,replace=TRUE)
    newdat&lt;-insurance
    newdat$new_y&lt;-fitted+new_resids
    fit&lt;-lm(new_y ~ smoker * bmi_c, data = newdat)
    coef(fit)
})

resid_resamp%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) smokeryes    bmi_c smokeryes:bmi_c
## 1    190.7226  414.6222 31.34086        66.49275</code></pre>
</div>
<div id="the-standard-errors-for-the-intercept-smokers-bmi-and-the-interaction-between-smokers-and-bmi-are-186.98-413.27-31.14-and-66.85-respectively.-the-intercept-and-smoker-ses-are-slightly-lower-than-the-original-ses-and-the-bmi_c-and-smoker-and-bmi_c-interaction-ses-are-pretty-similar.-compared-to-the-robust-ses-the-intercept-is-higher-the-smokers-are-lower-and-the-bmi-and-smoker-and-bmi_c-interaction-ses-are-once-again-very-similar." class="section level2">
<h2>The standard errors for the intercept, smokers, bmi, and the interaction between smokers and bmi are 186.98, 413.27, 31.14, and 66.85 respectively. The intercept and smoker SEs are slightly lower than the original SEs, and the bmi_c and smoker and bmi_c interaction SEs are pretty similar. Compared to the robust SEs, the intercept is higher, the smokers are lower, and the bmi and smoker and bmi_c interaction SEs are once again very similar.</h2>
<pre class="r"><code>library(tidyverse); library(lmtest)

data&lt;-insurance
data$y&lt;-ifelse(insurance$smoker==&quot;yes&quot;,1,0) 

fit&lt;-glm(y~bmi+charges,data=data,family=&quot;binomial&quot;(link=logit))
summary(fit)</code></pre>
<pre><code>##
## Call:
## glm(formula = y ~ bmi + charges, family = binomial(link
= logit),
## data = data)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -3.03644 -0.17739 -0.07688 -0.01864 1.94469
##
## Coefficients:
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 9.634e-01 6.748e-01 1.428 0.153
## bmi -2.831e-01 3.218e-02 -8.798 &lt;2e-16 ***
## charges 3.192e-04 2.115e-05 15.091 &lt;2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for binomial family taken to be 1)
##
## Null deviance: 1356.63 on 1337 degrees of freedom
## Residual deviance: 392.73 on 1335 degrees of freedom
## AIC: 398.73
##
## Number of Fisher Scoring iterations: 7</code></pre>
<pre class="r"><code>exp(coef(fit))%&gt;%round(3)</code></pre>
<pre><code>## (Intercept)         bmi     charges 
##       2.621       0.753       1.000</code></pre>
<pre class="r"><code>data$prob&lt;-predict(fit,type=&quot;response&quot;) 

table(predict=as.numeric(data$prob&gt;.5),truth=data$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict    0    1  Sum
##     0   1029   54 1083
##     1     35  220  255
##     Sum 1064  274 1338</code></pre>
<pre class="r"><code>#sensitivity
mean(data[data$y==1,]$prob&gt;.5)</code></pre>
<pre><code>## [1] 0.8029197</code></pre>
<pre class="r"><code>#specificity
mean(data[data$y==0,]$prob&lt;.5)</code></pre>
<pre><code>## [1] 0.9671053</code></pre>
<pre class="r"><code>#accuracy
(1064/1338)</code></pre>
<pre><code>## [1] 0.7952167</code></pre>
<pre class="r"><code>#precision
220/255</code></pre>
<pre><code>## [1] 0.8627451</code></pre>
<pre class="r"><code>data$logit&lt;-predict(fit,type=&quot;link&quot;) #get predicted logit scores (logodds)

data%&gt;%ggplot()+geom_density(aes(logit,color=smoker,fill=smoker), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;predictor (logit)&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC) 
ROCplot&lt;-ggplot(data)+geom_roc(aes(d=y,m=prob), n.cuts=0) 
ROCplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.9823229</code></pre>
</div>
<div id="if-there-were-0-changes-in-bmi-or-chargers-the-odds-of-being-a-smoker-are-2.621.-for-every-one-unit-increase-in-bmi-the-odds-of-being-a-smoker-change-by-0.753.-for-every-one-unit-increase-in-charges-the-odds-of-being-a-smoker-are-1x-that-of-the-intercept.-the-sensitivity-is-0.803-the-specificity-is-0.967-the-accuracy-is-0.795-and-the-precision-is-0.863.-the-auc-is-0.982.-the-auc-shows-how-good-the-predictions-of-our-model-are-and-with-an-auc-of-0.982-our-model-predicts-around-98.2-of-the-outcomes-whether-or-not-the-individual-is-a-smoker." class="section level2">
<h2>If there were 0 changes in BMI or Chargers, the odds of being a smoker are 2.621. For every one unit increase in BMI, the odds of being a smoker change by 0.753. For every one unit increase in charges, the odds of being a smoker are 1x that of the intercept. The sensitivity is 0.803, the specificity is 0.967, the accuracy is 0.795, and the precision is 0.863. The AUC is 0.982. The AUC shows how good the predictions of our model are, and with an AUC of 0.982, our model predicts around 98.2% of the outcomes (whether or not the individual is a smoker).</h2>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}

library(lmtest)
data=insurance
fit&lt;-glm(smoker~.,data=data,family=&quot;binomial&quot;)
coeftest(fit)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 5.50343158 1.07308863 5.1286 2.919e-07 ***
## age -0.10057901 0.01331266 -7.5551 4.184e-14 ***
## sexmale 0.54784585 0.30179340 1.8153 0.06948 .
## bmi -0.37077591 0.04622992 -8.0203 1.055e-15 ***
## children -0.24393817 0.12779894 -1.9088 0.05629 .
## regionnorthwest 0.14587682 0.39845914 0.3661 0.71429
## regionsoutheast 0.64194450 0.42059154 1.5263 0.12694
## regionsouthwest 0.31997422 0.43860613 0.7295 0.46568
## charges 0.00039342 0.00003114 12.6337 &lt; 2.2e-16 ***
## bmi_c NA NA NA NA
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit))%&gt;%round(3) </code></pre>
<pre><code>## (Intercept) age sexmale bmi children regionnorthwest
## 245.533 0.904 1.730 0.690 0.784 1.157
## regionsoutheast regionsouthwest charges bmi_c
## 1.900 1.377 1.000 NA</code></pre>
<pre class="r"><code>probs&lt;-predict(fit,type=&quot;response&quot;)
data$probs&lt;-predict(fit,type=&quot;response&quot;)
class_diag(probs, insurance$smoker)</code></pre>
<pre><code>##           acc      sens      spec       ppv       auc
## yes 0.9603886 0.9452555 0.9642857 0.8720539 0.9865094</code></pre>
<pre class="r"><code>table(predict=as.numeric(data$probs&gt;.5),truth=insurance$smoker)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   no  yes  Sum
##     0   1026   15 1041
##     1     38  259  297
##     Sum 1064  274 1338</code></pre>
<p>#Here, the variable “smoker” is being compared to all other variables in the insurance dataset. When running classification diagnositcs, the accuracy is 0.960, the sensitivity is 0.945, the specificity is 0.964, the precision is 0.872, and the auc is 0.987. This means that 98.7% of our model is correctly predicted (whether or not the individual is a smoker) by the other variables.</p>
<pre class="r"><code>set.seed(1234)
k=10
data &lt;- insurance %&gt;% sample_frac 
folds &lt;- ntile(1:nrow(data),n=10) 

diags&lt;-NULL
for(i in 1:k){
  train &lt;- data[folds!=i,] 
  test &lt;- data[folds==i,] 
  truth &lt;- test$smoker 
  
  fit &lt;- glm(smoker~., data=insurance, family=&quot;binomial&quot;)
  probs &lt;- predict(fit, newdata=test, type=&quot;response&quot;)
  
  diags&lt;-rbind(diags,class_diag(probs,truth))
}

summarize_all(diags,mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.9604085 0.9471491 0.9644623 0.8752178 0.9872734</code></pre>
</div>
<div id="when-running-the-10-fold-cross-validation-we-get-an-accuracy-of-0.960-a-sensitivity-of-0.947-a-specificity-of-0.964-a-precision-of-0.875-and-an-auc-of-0.987.-compared-to-the-in-sample-statistics-all-of-the-diagnositcs-are-within-.01-of-each-other-meaning-they-are-very-similar." class="section level2">
<h2>When running the 10-fold cross validation, we get an accuracy of 0.960, a sensitivity of 0.947, a specificity of 0.964, a precision of 0.875, and an auc of 0.987. Compared to the in-sample statistics, all of the diagnositcs are within .01 of each other, meaning they are very similar.</h2>
<pre class="r"><code>library(glmnet)
set.seed(1234)

model.matrix(smoker~.,data=insurance)[,-1]</code></pre>
<pre><code>## age sexmale bmi children regionnorthwest regionsoutheast
regionsouthwest charges
## 1 19 0 27.900 0 0 0 1 16884.924
## 2 18 1 33.770 1 0 1 0 1725.552
## 3 28 1 33.000 3 0 1 0 4449.462
## 4 33 1 22.705 0 1 0 0 21984.471
## 5 32 1 28.880 0 1 0 0 3866.855
## 6 31 0 25.740 0 0 1 0 3756.622
## 7 46 0 33.440 1 0 1 0 8240.590
## 8 37 0 27.740 3 1 0 0 7281.506
## 9 37 1 29.830 2 0 0 0 6406.411
## 10 60 0 25.840 0 1 0 0 28923.137
## 11 25 1 26.220 0 0 0 0 2721.321
## 12 62 0 26.290 0 0 1 0 27808.725
## 13 23 1 34.400 0 0 0 1 1826.843
## 14 56 0 39.820 0 0 1 0 11090.718
## 15 27 1 42.130 0 0 1 0 39611.758
## 16 19 1 24.600 1 0 0 1 1837.237
## 17 52 0 30.780 1 0 0 0 10797.336
## 18 23 1 23.845 0 0 0 0 2395.172
## 19 56 1 40.300 0 0 0 1 10602.385
## 20 30 1 35.300 0 0 0 1 36837.467
## 21 60 0 36.005 0 0 0 0 13228.847
## 22 30 0 32.400 1 0 0 1 4149.736
## 23 18 1 34.100 0 0 1 0 1137.011
## 24 34 0 31.920 1 0 0 0 37701.877
## 25 37 1 28.025 2 1 0 0 6203.902
## 26 59 0 27.720 3 0 1 0 14001.134
## 27 63 0 23.085 0 0 0 0 14451.835
## 28 55 0 32.775 2 1 0 0 12268.632
## 29 23 1 17.385 1 1 0 0 2775.192
## 30 31 1 36.300 2 0 0 1 38711.000
## 31 22 1 35.600 0 0 0 1 35585.576
## 32 18 0 26.315 0 0 0 0 2198.190
## 33 19 0 28.600 5 0 0 1 4687.797
## 34 63 1 28.310 0 1 0 0 13770.098
## 35 28 1 36.400 1 0 0 1 51194.559
## 36 19 1 20.425 0 1 0 0 1625.434
## 37 62 0 32.965 3 1 0 0 15612.193
## 38 26 1 20.800 0 0 0 1 2302.300
## 39 35 1 36.670 1 0 0 0 39774.276
## 40 60 1 39.900 0 0 0 1 48173.361
## 41 24 0 26.600 0 0 0 0 3046.062
## 42 31 0 36.630 2 0 1 0 4949.759
## 43 41 1 21.780 1 0 1 0 6272.477
## 44 37 0 30.800 2 0 1 0 6313.759
## 45 38 1 37.050 1 0 0 0 6079.672
## 46 55 1 37.300 0 0 0 1 20630.284
## 47 18 0 38.665 2 0 0 0 3393.356
## 48 28 0 34.770 0 1 0 0 3556.922
## 49 60 0 24.530 0 0 1 0 12629.897
## 50 36 1 35.200 1 0 1 0 38709.176
## 51 18 0 35.625 0 0 0 0 2211.131
## 52 21 0 33.630 2 1 0 0 3579.829
## 53 48 1 28.000 1 0 0 1 23568.272
## 54 36 1 34.430 0 0 1 0 37742.576
## 55 40 0 28.690 3 1 0 0 8059.679
## 56 58 1 36.955 2 1 0 0 47496.494
## 57 58 0 31.825 2 0 0 0 13607.369
## 58 18 1 31.680 2 0 1 0 34303.167
## 59 53 0 22.880 1 0 1 0 23244.790
## 60 34 0 37.335 2 1 0 0 5989.524
## 61 43 1 27.360 3 0 0 0 8606.217
## 62 25 1 33.660 4 0 1 0 4504.662
## 63 64 1 24.700 1 1 0 0 30166.618
## 64 28 0 25.935 1 1 0 0 4133.642
## 65 20 0 22.420 0 1 0 0 14711.744
## 66 19 0 28.900 0 0 0 1 1743.214
## 67 61 0 39.100 2 0 0 1 14235.072
## 68 40 1 26.315 1 1 0 0 6389.378
## 69 40 0 36.190 0 0 1 0 5920.104
## 70 28 1 23.980 3 0 1 0 17663.144
## 71 27 0 24.750 0 0 1 0 16577.780
## 72 31 1 28.500 5 0 0 0 6799.458
## 73 53 0 28.100 3 0 0 1 11741.726
## 74 58 1 32.010 1 0 1 0 11946.626
## 75 44 1 27.400 2 0 0 1 7726.854
## 76 57 1 34.010 0 1 0 0 11356.661
## 77 29 0 29.590 1 0 1 0 3947.413
## 78 21 1 35.530 0 0 1 0 1532.470
## 79 22 0 39.805 0 0 0 0 2755.021
## 80 41 0 32.965 0 1 0 0 6571.024
## 81 31 1 26.885 1 0 0 0 4441.213
## 82 45 0 38.285 0 0 0 0 7935.291
## 83 22 1 37.620 1 0 1 0 37165.164
## 84 48 0 41.230 4 1 0 0 11033.662
## 85 37 0 34.800 2 0 0 1 39836.519
## 86 45 1 22.895 2 1 0 0 21098.554
## 87 57 0 31.160 0 1 0 0 43578.939
## 88 56 0 27.200 0 0 0 1 11073.176
## 89 46 0 27.740 0 1 0 0 8026.667
## 90 55 0 26.980 0 1 0 0 11082.577
## 91 21 0 39.490 0 0 1 0 2026.974
## 92 53 0 24.795 1 1 0 0 10942.132
## 93 59 1 29.830 3 0 0 0 30184.937
## 94 35 1 34.770 2 1 0 0 5729.005
## 95 64 0 31.300 2 0 0 1 47291.055
## 96 28 0 37.620 1 0 1 0 3766.884
## 97 54 0 30.800 3 0 0 1 12105.320
## 98 55 1 38.280 0 0 1 0 10226.284
## 99 56 1 19.950 0 0 0 0 22412.648
## 100 38 1 19.300 0 0 0 1 15820.699
## 101 41 0 31.600 0 0 0 1 6186.127
## 102 30 1 25.460 0 0 0 0 3645.089
## 103 18 0 30.115 0 0 0 0 21344.847
## 104 61 0 29.920 3 0 1 0 30942.192
## 105 34 0 27.500 1 0 0 1 5003.853
## 106 20 1 28.025 1 1 0 0 17560.380
## 107 19 0 28.400 1 0 0 1 2331.519
## 108 26 1 30.875 2 1 0 0 3877.304
## 109 29 1 27.940 0 0 1 0 2867.120
## 110 63 1 35.090 0 0 1 0 47055.532
## 111 54 1 33.630 1 1 0 0 10825.254
## 112 55 0 29.700 2 0 0 1 11881.358
## 113 37 1 30.800 0 0 0 1 4646.759
## 114 21 0 35.720 0 1 0 0 2404.734
## 115 52 1 32.205 3 0 0 0 11488.317
## 116 60 1 28.595 0 0 0 0 30259.996
## 117 58 1 49.060 0 0 1 0 11381.325
## 118 29 0 27.940 1 0 1 0 19107.780
## 119 49 0 27.170 0 0 1 0 8601.329
## 120 37 0 23.370 2 1 0 0 6686.431
## 121 44 1 37.100 2 0 0 1 7740.337
## 122 18 1 23.750 0 0 0 0 1705.624
## 123 20 0 28.975 0 1 0 0 2257.475
## 124 44 1 31.350 1 0 0 0 39556.495
## 125 47 0 33.915 3 1 0 0 10115.009
## 126 26 0 28.785 0 0 0 0 3385.399
## 127 19 0 28.300 0 0 0 1 17081.080
## 128 52 0 37.400 0 0 0 1 9634.538
## 129 32 0 17.765 2 1 0 0 32734.186
## 130 38 1 34.700 2 0 0 1 6082.405
## 131 59 0 26.505 0 0 0 0 12815.445
## 132 61 0 22.040 0 0 0 0 13616.359
## 133 53 0 35.900 2 0 0 1 11163.568
## 134 19 1 25.555 0 1 0 0 1632.564
## 135 20 0 28.785 0 0 0 0 2457.211
## 136 22 0 28.050 0 0 1 0 2155.682
## 137 19 1 34.100 0 0 0 1 1261.442
## 138 22 1 25.175 0 1 0 0 2045.685
## 139 54 0 31.900 3 0 1 0 27322.734
## 140 22 0 36.000 0 0 0 1 2166.732
## 141 34 1 22.420 2 0 0 0 27375.905
## 142 26 1 32.490 1 0 0 0 3490.549
## 143 34 1 25.300 2 0 1 0 18972.495
## 144 29 1 29.735 2 1 0 0 18157.876
## 145 30 1 28.690 3 1 0 0 20745.989
## 146 29 0 38.830 3 0 1 0 5138.257
## 147 46 1 30.495 3 1 0 0 40720.551
## 148 51 0 37.730 1 0 1 0 9877.608
## 149 53 0 37.430 1 1 0 0 10959.695
## 150 19 1 28.400 1 0 0 1 1842.519
## 151 35 1 24.130 1 1 0 0 5125.216
## 152 48 1 29.700 0 0 1 0 7789.635
## 153 32 0 37.145 3 0 0 0 6334.344
## 154 42 0 23.370 0 0 0 0 19964.746
## 155 40 0 25.460 1 0 0 0 7077.189
## 156 44 1 39.520 0 1 0 0 6948.701
## 157 48 1 24.420 0 0 1 0 21223.676
## 158 18 1 25.175 0 0 0 0 15518.180
## 159 30 1 35.530 0 0 1 0 36950.257
## 160 50 0 27.830 3 0 1 0 19749.383
## 161 42 0 26.600 0 1 0 0 21348.706
## 162 18 0 36.850 0 0 1 0 36149.484
## 163 54 1 39.600 1 0 0 1 10450.552
## 164 32 0 29.800 2 0 0 1 5152.134
## 165 37 1 29.640 0 1 0 0 5028.147
## 166 47 1 28.215 4 0 0 0 10407.086
## 167 20 0 37.000 5 0 0 1 4830.630
## 168 32 0 33.155 3 1 0 0 6128.797
## 169 19 0 31.825 1 1 0 0 2719.280
## 170 27 1 18.905 3 0 0 0 4827.905
## 171 63 1 41.470 0 0 1 0 13405.390
## 172 49 1 30.300 0 0 0 1 8116.680
## 173 18 1 15.960 0 0 0 0 1694.796
## 174 35 0 34.800 1 0 0 1 5246.047
## 175 24 0 33.345 0 1 0 0 2855.438
## 176 63 0 37.700 0 0 0 1 48824.450
## 177 38 1 27.835 2 1 0 0 6455.863
## 178 54 1 29.200 1 0 0 1 10436.096
## 179 46 0 28.900 2 0 0 1 8823.279
## 180 41 0 33.155 3 0 0 0 8538.288
## 181 58 1 28.595 0 1 0 0 11735.879
## 182 18 0 38.280 0 0 1 0 1631.821
## 183 22 1 19.950 3 0 0 0 4005.423
## 184 44 0 26.410 0 1 0 0 7419.478
## 185 44 1 30.690 2 0 1 0 7731.427
## 186 36 1 41.895 3 0 0 0 43753.337
## 187 26 0 29.920 2 0 1 0 3981.977
## 188 30 0 30.900 3 0 0 1 5325.651
## 189 41 0 32.200 1 0 0 1 6775.961
## 190 29 0 32.110 2 1 0 0 4922.916
## 191 61 1 31.570 0 0 1 0 12557.605
## 192 36 0 26.200 0 0 0 1 4883.866
## 193 25 1 25.740 0 0 1 0 2137.654
## 194 56 0 26.600 1 1 0 0 12044.342
## 195 18 1 34.430 0 0 1 0 1137.470
## 196 19 1 30.590 0 1 0 0 1639.563
## 197 39 0 32.800 0 0 0 1 5649.715
## 198 45 0 28.600 2 0 1 0 8516.829
## 199 51 0 18.050 0 1 0 0 9644.253
## 200 64 0 39.330 0 0 0 0 14901.517
## 201 19 0 32.110 0 1 0 0 2130.676
## 202 48 0 32.230 1 0 1 0 8871.152
## 203 60 0 24.035 0 1 0 0 13012.209
## 204 27 0 36.080 0 0 1 0 37133.898
## 205 46 1 22.300 0 0 0 1 7147.105
## 206 28 0 28.880 1 0 0 0 4337.735
## 207 59 1 26.400 0 0 1 0 11743.299
## 208 35 1 27.740 2 0 0 0 20984.094
## 209 63 0 31.800 0 0 0 1 13880.949
## 210 40 1 41.230 1 0 0 0 6610.110
## 211 20 1 33.000 1 0 0 1 1980.070
## 212 40 1 30.875 4 1 0 0 8162.716
## 213 24 1 28.500 2 1 0 0 3537.703
## 214 34 0 26.730 1 0 1 0 5002.783
## 215 45 0 30.900 2 0 0 1 8520.026
## 216 41 0 37.100 2 0 0 1 7371.772
## 217 53 0 26.600 0 1 0 0 10355.641
## 218 27 1 23.100 0 0 1 0 2483.736
## 219 26 0 29.920 1 0 1 0 3392.977
## 220 24 0 23.210 0 0 1 0 25081.768
## 221 34 0 33.700 1 0 0 1 5012.471
## 222 53 0 33.250 0 0 0 0 10564.885
## 223 32 1 30.800 3 0 0 1 5253.524
## 224 19 1 34.800 0 0 0 1 34779.615
## 225 42 1 24.640 0 0 1 0 19515.542
## 226 55 1 33.880 3 0 1 0 11987.168
## 227 28 1 38.060 0 0 1 0 2689.495
## 228 58 0 41.910 0 0 1 0 24227.337
## 229 41 0 31.635 1 0 0 0 7358.176
## 230 47 1 25.460 2 0 0 0 9225.256
## 231 42 0 36.195 1 1 0 0 7443.643
## 232 59 0 27.830 3 0 1 0 14001.287
## 233 19 0 17.800 0 0 0 1 1727.785
## 234 59 1 27.500 1 0 0 1 12333.828
## 235 39 1 24.510 2 1 0 0 6710.192
## 236 40 0 22.220 2 0 1 0 19444.266
## 237 18 0 26.730 0 0 1 0 1615.767
## 238 31 1 38.390 2 0 1 0 4463.205
## 239 19 1 29.070 0 1 0 0 17352.680
## 240 44 1 38.060 1 0 1 0 7152.671
## 241 23 0 36.670 2 0 0 0 38511.628
## 242 33 0 22.135 1 0 0 0 5354.075
## 243 55 0 26.800 1 0 0 1 35160.135
## 244 40 1 35.300 3 0 0 1 7196.867
## 245 63 0 27.740 0 0 0 0 29523.166
## 246 54 1 30.020 0 1 0 0 24476.479
## 247 60 0 38.060 0 0 1 0 12648.703
## 248 24 1 35.860 0 0 1 0 1986.933
## 249 19 1 20.900 1 0 0 1 1832.094
## 250 29 1 28.975 1 0 0 0 4040.558
## 251 18 1 17.290 2 0 0 0 12829.455
## 252 63 0 32.200 2 0 0 1 47305.305
## 253 54 1 34.210 2 0 1 0 44260.750
## 254 27 1 30.300 3 0 0 1 4260.744
## 255 50 1 31.825 0 0 0 0 41097.162
## 256 55 0 25.365 3 0 0 0 13047.332
## 257 56 1 33.630 0 1 0 0 43921.184
## 258 38 0 40.150 0 0 1 0 5400.980
## 259 51 1 24.415 4 1 0 0 11520.100
## 260 19 1 31.920 0 1 0 0 33750.292
## 261 58 0 25.200 0 0 0 1 11837.160
## 262 20 0 26.840 1 0 1 0 17085.268
## 263 52 1 24.320 3 0 0 0 24869.837
## 264 19 1 36.955 0 1 0 0 36219.405
## 265 53 0 38.060 3 0 1 0 20462.998
## 266 46 1 42.350 3 0 1 0 46151.124
## 267 40 1 19.800 1 0 1 0 17179.522
## 268 59 0 32.395 3 0 0 0 14590.632
## 269 45 1 30.200 1 0 0 1 7441.053
## 270 49 1 25.840 1 0 0 0 9282.481
## 271 18 1 29.370 1 0 1 0 1719.436
## 272 50 1 34.200 2 0 0 1 42856.838
## 273 41 1 37.050 2 1 0 0 7265.703
## 274 50 1 27.455 1 0 0 0 9617.662
## 275 25 1 27.550 0 1 0 0 2523.169
## 276 47 0 26.600 2 0 0 0 9715.841
## 277 19 1 20.615 2 1 0 0 2803.698
## 278 22 0 24.300 0 0 0 1 2150.469
## 279 59 1 31.790 2 0 1 0 12928.791
## 280 51 0 21.560 1 0 1 0 9855.131
## 281 40 0 28.120 1 0 0 0 22331.567
## 282 54 1 40.565 3 0 0 0 48549.178
## 283 30 1 27.645 1 0 0 0 4237.127
## 284 55 0 32.395 1 0 0 0 11879.104
## 285 52 0 31.200 0 0 0 1 9625.920
## 286 46 1 26.620 1 0 1 0 7742.110
## 287 46 0 48.070 2 0 0 0 9432.925
## 288 63 0 26.220 0 1 0 0 14256.193
## 289 59 0 36.765 1 0 0 0 47896.791
## 290 52 1 26.400 3 0 1 0 25992.821
## 291 28 0 33.400 0 0 0 1 3172.018
## 292 29 1 29.640 1 0 0 0 20277.808
## 293 25 1 45.540 2 0 1 0 42112.236
## 294 22 0 28.820 0 0 1 0 2156.752
## 295 25 1 26.800 3 0 0 1 3906.127
## 296 18 1 22.990 0 0 0 0 1704.568
## 297 19 1 27.700 0 0 0 1 16297.846
## 298 47 1 25.410 1 0 1 0 21978.677
## 299 31 1 34.390 3 1 0 0 38746.355
## 300 48 0 28.880 1 1 0 0 9249.495
## 301 36 1 27.550 3 0 0 0 6746.743
## 302 53 0 22.610 3 0 0 0 24873.385
## 303 56 0 37.510 2 0 1 0 12265.507
## 304 28 0 33.000 2 0 1 0 4349.462
## 305 57 0 38.000 2 0 0 1 12646.207
## 306 29 1 33.345 2 1 0 0 19442.354
## 307 28 0 27.500 2 0 0 1 20177.671
## 308 30 0 33.330 1 0 1 0 4151.029
## 309 58 1 34.865 0 0 0 0 11944.594
## 310 41 0 33.060 2 1 0 0 7749.156
## 311 50 1 26.600 0 0 0 1 8444.474
## 312 19 0 24.700 0 0 0 1 1737.376
## 313 43 1 35.970 3 0 1 0 42124.515
## 314 49 1 35.860 0 0 1 0 8124.408
## 315 27 0 31.400 0 0 0 1 34838.873
## 316 52 1 33.250 0 0 0 0 9722.770
## 317 50 1 32.205 0 1 0 0 8835.265
## 318 54 1 32.775 0 0 0 0 10435.065
## 319 44 0 27.645 0 1 0 0 7421.195
## 320 32 1 37.335 1 0 0 0 4667.608
## 321 34 1 25.270 1 1 0 0 4894.753
## 322 26 0 29.640 4 0 0 0 24671.663
## 323 34 1 30.800 0 0 0 1 35491.640
## 324 57 1 40.945 0 0 0 0 11566.301
## 325 29 1 27.200 0 0 0 1 2866.091
## 326 40 1 34.105 1 0 0 0 6600.206
## 327 27 0 23.210 1 0 1 0 3561.889
## 328 45 1 36.480 2 1 0 0 42760.502
## 329 64 0 33.800 1 0 0 1 47928.030
## 330 52 1 36.700 0 0 0 1 9144.565
## 331 61 0 36.385 1 0 0 0 48517.563
## 332 52 1 27.360 0 1 0 0 24393.622
## 333 61 0 31.160 0 1 0 0 13429.035
## 334 56 0 28.785 0 0 0 0 11658.379
## 335 43 0 35.720 2 0 0 0 19144.577
## 336 64 1 34.500 0 0 0 1 13822.803
## 337 60 1 25.740 0 0 1 0 12142.579
## 338 62 1 27.550 1 1 0 0 13937.666
## 339 50 1 32.300 1 0 0 0 41919.097
## 340 46 0 27.720 1 0 1 0 8232.639
## 341 24 0 27.600 0 0 0 1 18955.220
## 342 62 1 30.020 0 1 0 0 13352.100
## 343 60 0 27.550 0 0 0 0 13217.094
## 344 63 1 36.765 0 0 0 0 13981.850
## 345 49 0 41.470 4 0 1 0 10977.206
## 346 34 0 29.260 3 0 1 0 6184.299
## 347 33 1 35.750 2 0 1 0 4889.999
## 348 46 1 33.345 1 0 0 0 8334.458
## 349 36 0 29.920 1 0 1 0 5478.037
## 350 19 1 27.835 0 1 0 0 1635.734
## 351 57 0 23.180 0 1 0 0 11830.607
## 352 50 0 25.600 0 0 0 1 8932.084
## 353 30 0 27.700 0 0 0 1 3554.203
## 354 33 1 35.245 0 0 0 0 12404.879
## 355 18 0 38.280 0 0 1 0 14133.038
## 356 46 1 27.600 0 0 0 1 24603.048
## 357 46 1 43.890 3 0 1 0 8944.115
## 358 47 1 29.830 3 1 0 0 9620.331
## 359 23 1 41.910 0 0 1 0 1837.282
## 360 18 0 20.790 0 0 1 0 1607.510
## 361 48 0 32.300 2 0 0 0 10043.249
## 362 35 1 30.500 1 0 0 1 4751.070
## 363 19 0 21.700 0 0 0 1 13844.506
## 364 21 0 26.400 1 0 0 1 2597.779
## 365 21 0 21.890 2 0 1 0 3180.510
## 366 49 0 30.780 1 0 0 0 9778.347
## 367 56 0 32.300 3 0 0 0 13430.265
## 368 42 0 24.985 2 1 0 0 8017.061
## 369 44 1 32.015 2 1 0 0 8116.269
## 370 18 1 30.400 3 0 0 0 3481.868
## 371 61 0 21.090 0 1 0 0 13415.038
## 372 57 0 22.230 0 0 0 0 12029.287
## 373 42 0 33.155 1 0 0 0 7639.417
## 374 26 1 32.900 2 0 0 1 36085.219
## 375 20 1 33.330 0 0 1 0 1391.529
## 376 23 0 28.310 0 1 0 0 18033.968
## 377 39 0 24.890 3 0 0 0 21659.930
## 378 24 1 40.150 0 0 1 0 38126.247
## 379 64 0 30.115 3 1 0 0 16455.708
## 380 62 1 31.460 1 0 1 0 27000.985
## 381 27 0 17.955 2 0 0 0 15006.579
## 382 55 1 30.685 0 0 0 0 42303.692
## 383 55 1 33.000 0 0 1 0 20781.489
## 384 35 0 43.340 2 0 1 0 5846.918
## 385 44 1 22.135 2 0 0 0 8302.536
## 386 19 1 34.400 0 0 0 1 1261.859
## 387 58 0 39.050 0 0 1 0 11856.412
## 388 50 1 25.365 2 1 0 0 30284.643
## 389 26 0 22.610 0 1 0 0 3176.816
## 390 24 0 30.210 3 1 0 0 4618.080
## 391 48 1 35.625 4 0 0 0 10736.871
## 392 19 0 37.430 0 1 0 0 2138.071
## 393 48 1 31.445 1 0 0 0 8964.061
## 394 49 1 31.350 1 0 0 0 9290.139
## 395 46 0 32.300 2 0 0 0 9411.005
## 396 46 1 19.855 0 1 0 0 7526.706
## 397 43 0 34.400 3 0 0 1 8522.003
## 398 21 1 31.020 0 0 1 0 16586.498
## 399 64 1 25.600 2 0 0 1 14988.432
## 400 18 0 38.170 0 0 1 0 1631.668
## 401 51 0 20.600 0 0 0 1 9264.797
## 402 47 1 47.520 1 0 1 0 8083.920
## 403 64 0 32.965 0 1 0 0 14692.669
## 404 49 1 32.300 3 1 0 0 10269.460
## 405 31 1 20.400 0 0 0 1 3260.199
## 406 52 0 38.380 2 0 0 0 11396.900
## 407 33 0 24.310 0 0 1 0 4185.098
## 408 47 0 23.600 1 0 0 1 8539.671
## 409 38 1 21.120 3 0 1 0 6652.529
## 410 32 1 30.030 1 0 1 0 4074.454
## 411 19 1 17.480 0 1 0 0 1621.340
## 412 44 0 20.235 1 0 0 0 19594.810
## 413 26 0 17.195 2 0 0 0 14455.644
## 414 25 1 23.900 5 0 0 1 5080.096
## 415 19 0 35.150 0 1 0 0 2134.901
## 416 43 0 35.640 1 0 1 0 7345.727
## 417 52 1 34.100 0 0 1 0 9140.951
## 418 36 0 22.600 2 0 0 1 18608.262
## 419 64 1 39.160 1 0 1 0 14418.280
## 420 63 0 26.980 0 1 0 0 28950.469
## 421 64 1 33.880 0 0 1 0 46889.261
## 422 61 1 35.860 0 0 1 0 46599.108
## 423 40 1 32.775 1 0 0 0 39125.332
## 424 25 1 30.590 0 0 0 0 2727.395
## 425 48 1 30.200 2 0 0 1 8968.330
## 426 45 1 24.310 5 0 1 0 9788.866
## 427 38 0 27.265 1 0 0 0 6555.070
## 428 18 0 29.165 0 0 0 0 7323.735
## 429 21 0 16.815 1 0 0 0 3167.456
## 430 27 0 30.400 3 1 0 0 18804.752
## 431 19 1 33.100 0 0 0 1 23082.955
## 432 29 0 20.235 2 1 0 0 4906.410
## 433 42 1 26.900 0 0 0 1 5969.723
## 434 60 0 30.500 0 0 0 1 12638.195
## 435 31 1 28.595 1 1 0 0 4243.590
## 436 60 1 33.110 3 0 1 0 13919.823
## 437 22 1 31.730 0 0 0 0 2254.797
## 438 35 1 28.900 3 0 0 1 5926.846
## 439 52 0 46.750 5 0 1 0 12592.534
## 440 26 1 29.450 0 0 0 0 2897.323
## 441 31 0 32.680 1 1 0 0 4738.268
## 442 33 0 33.500 0 0 0 1 37079.372
## 443 18 1 43.010 0 0 1 0 1149.396
## 444 59 0 36.520 1 0 1 0 28287.898
## 445 56 1 26.695 1 1 0 0 26109.329
## 446 45 0 33.100 0 0 0 1 7345.084
## 447 60 1 29.640 0 0 0 0 12731.000
## 448 56 0 25.650 0 1 0 0 11454.022
## 449 40 0 29.600 0 0 0 1 5910.944
## 450 35 1 38.600 1 0 0 1 4762.329
## 451 39 1 29.600 4 0 0 1 7512.267
## 452 30 1 24.130 1 1 0 0 4032.241
## 453 24 1 23.400 0 0 0 1 1969.614
## 454 20 1 29.735 0 1 0 0 1769.532
## 455 32 1 46.530 2 0 1 0 4686.389
## 456 59 1 37.400 0 0 0 1 21797.000
## 457 55 0 30.140 2 0 1 0 11881.970
## 458 57 0 30.495 0 1 0 0 11840.775
## 459 56 1 39.600 0 0 0 1 10601.412
## 460 40 0 33.000 3 0 1 0 7682.670
## 461 49 0 36.630 3 0 1 0 10381.479
## 462 42 1 30.000 0 0 0 1 22144.032
## 463 62 0 38.095 2 0 0 0 15230.324
## 464 56 1 25.935 0 0 0 0 11165.418
## 465 19 1 25.175 0 1 0 0 1632.036
## 466 30 0 28.380 1 0 1 0 19521.968
## 467 60 0 28.700 1 0 0 1 13224.693
## 468 56 0 33.820 2 1 0 0 12643.378
## 469 28 0 24.320 1 0 0 0 23288.928
## 470 18 0 24.090 1 0 1 0 2201.097
## 471 27 1 32.670 0 0 1 0 2497.038
## 472 18 0 30.115 0 0 0 0 2203.472
## 473 19 0 29.800 0 0 0 1 1744.465
## 474 47 0 33.345 0 0 0 0 20878.784
## 475 54 1 25.100 3 0 0 1 25382.297
## 476 61 1 28.310 1 1 0 0 28868.664
## 477 24 1 28.500 0 0 0 0 35147.528
## 478 25 1 35.625 0 1 0 0 2534.394
## 479 21 1 36.850 0 0 1 0 1534.304
## 480 23 1 32.560 0 0 1 0 1824.285
## 481 63 1 41.325 3 1 0 0 15555.189
## 482 49 1 37.510 2 0 1 0 9304.702
## 483 18 0 31.350 0 0 1 0 1622.188
## 484 51 0 39.500 1 0 0 1 9880.068
## 485 48 1 34.300 3 0 0 1 9563.029
## 486 31 0 31.065 0 0 0 0 4347.023
## 487 54 0 21.470 3 1 0 0 12475.351
## 488 19 1 28.700 0 0 0 1 1253.936
## 489 44 0 38.060 0 0 1 0 48885.136
## 490 53 1 31.160 1 1 0 0 10461.979
## 491 19 0 32.900 0 0 0 1 1748.774
## 492 61 0 25.080 0 0 1 0 24513.091
## 493 18 0 25.080 0 0 0 0 2196.473
## 494 61 1 43.400 0 0 0 1 12574.049
## 495 21 1 25.700 4 0 0 1 17942.106
## 496 20 1 27.930 0 0 0 0 1967.023
## 497 31 0 23.600 2 0 0 1 4931.647
## 498 45 1 28.700 2 0 0 1 8027.968
## 499 44 0 23.980 2 0 1 0 8211.100
## 500 62 0 39.200 0 0 0 1 13470.860
## 501 29 1 34.400 0 0 0 1 36197.699
## 502 43 1 26.030 0 0 0 0 6837.369
## 503 51 1 23.210 1 0 1 0 22218.115
## 504 19 1 30.250 0 0 1 0 32548.340
## 505 38 0 28.930 1 0 1 0 5974.385
## 506 37 1 30.875 3 1 0 0 6796.863
## 507 22 1 31.350 1 1 0 0 2643.269
## 508 21 1 23.750 2 1 0 0 3077.095
## 509 24 0 25.270 0 0 0 0 3044.213
## 510 57 0 28.700 0 0 0 1 11455.280
## 511 56 1 32.110 1 0 0 0 11763.001
## 512 27 1 33.660 0 0 1 0 2498.414
## 513 51 1 22.420 0 0 0 0 9361.327
## 514 19 1 30.400 0 0 0 1 1256.299
## 515 39 1 28.300 1 0 0 1 21082.160
## 516 58 1 35.700 0 0 0 1 11362.755
## 517 20 1 35.310 1 0 1 0 27724.289
## 518 45 1 30.495 2 1 0 0 8413.463
## 519 35 0 31.000 1 0 0 1 5240.765
## 520 31 1 30.875 0 0 0 0 3857.759
## 521 50 0 27.360 0 0 0 0 25656.575
## 522 32 0 44.220 0 0 1 0 3994.178
## 523 51 0 33.915 0 0 0 0 9866.305
## 524 38 0 37.730 0 0 1 0 5397.617
## 525 42 1 26.070 1 0 1 0 38245.593
## 526 18 0 33.880 0 0 1 0 11482.635
## 527 19 0 30.590 2 1 0 0 24059.680
## 528 51 0 25.800 1 0 0 1 9861.025
## 529 46 1 39.425 1 0 0 0 8342.909
## 530 18 1 25.460 0 0 0 0 1708.001
## 531 57 1 42.130 1 0 1 0 48675.518
## 532 62 0 31.730 0 0 0 0 14043.477
## 533 59 1 29.700 2 0 1 0 12925.886
## 534 37 1 36.190 0 0 1 0 19214.706
## 535 64 1 40.480 0 0 1 0 13831.115
## 536 38 1 28.025 1 0 0 0 6067.127
## 537 33 0 38.900 3 0 0 1 5972.378
## 538 46 0 30.200 2 0 0 1 8825.086
## 539 46 0 28.050 1 0 1 0 8233.097
## 540 53 1 31.350 0 0 1 0 27346.042
## 541 34 0 38.000 3 0 0 1 6196.448
## 542 20 0 31.790 2 0 1 0 3056.388
## 543 63 0 36.300 0 0 1 0 13887.204
## 544 54 0 47.410 0 0 1 0 63770.428
## 545 54 1 30.210 0 1 0 0 10231.500
## 546 49 1 25.840 2 1 0 0 23807.241
## 547 28 1 35.435 0 0 0 0 3268.847
## 548 54 0 46.700 2 0 0 1 11538.421
## 549 25 0 28.595 0 0 0 0 3213.622
## 550 43 0 46.200 0 0 1 0 45863.205
## 551 63 1 30.800 0 0 0 1 13390.559
## 552 32 0 28.930 0 0 1 0 3972.925
## 553 62 1 21.400 0 0 0 1 12957.118
## 554 52 0 31.730 2 1 0 0 11187.657
## 555 25 0 41.325 0 0 0 0 17878.901
## 556 28 1 23.800 2 0 0 1 3847.674
## 557 46 1 33.440 1 0 0 0 8334.590
## 558 34 1 34.210 0 0 1 0 3935.180
## 559 35 0 34.105 3 1 0 0 39983.426
## 560 19 1 35.530 0 1 0 0 1646.430
## 561 46 0 19.950 2 1 0 0 9193.838
## 562 54 0 32.680 0 0 0 0 10923.933
## 563 27 1 30.500 0 0 0 1 2494.022
## 564 50 1 44.770 1 0 1 0 9058.730
## 565 18 0 32.120 2 0 1 0 2801.259
## 566 19 0 30.495 0 1 0 0 2128.431
## 567 38 0 40.565 1 1 0 0 6373.557
## 568 41 1 30.590 2 1 0 0 7256.723
## 569 49 0 31.900 5 0 0 1 11552.904
## 570 48 1 40.565 2 1 0 0 45702.022
## 571 31 0 29.100 0 0 0 1 3761.292
## 572 18 0 37.290 1 0 1 0 2219.445
## 573 30 0 43.120 2 0 1 0 4753.637
## 574 62 0 36.860 1 0 0 0 31620.001
## 575 57 0 34.295 2 0 0 0 13224.057
## 576 58 0 27.170 0 1 0 0 12222.898
## 577 22 1 26.840 0 0 1 0 1665.000
## 578 31 0 38.095 1 0 0 0 58571.074
## 579 52 1 30.200 1 0 0 1 9724.530
## 580 25 0 23.465 0 0 0 0 3206.491
## 581 59 1 25.460 1 0 0 0 12913.992
## 582 19 1 30.590 0 1 0 0 1639.563
## 583 39 1 45.430 2 0 1 0 6356.271
## 584 32 0 23.650 1 0 1 0 17626.240
## 585 19 1 20.700 0 0 0 1 1242.816
## 586 33 0 28.270 1 0 1 0 4779.602
## 587 21 1 20.235 3 0 0 0 3861.210
## 588 34 0 30.210 1 1 0 0 43943.876
## 589 61 0 35.910 0 0 0 0 13635.638
## 590 38 0 30.690 1 0 1 0 5976.831
## 591 58 0 29.000 0 0 0 1 11842.442
## 592 47 1 19.570 1 1 0 0 8428.069
## 593 20 1 31.130 2 0 1 0 2566.471
## 594 21 0 21.850 1 0 0 0 15359.104
## 595 41 1 40.260 0 0 1 0 5709.164
## 596 46 0 33.725 1 0 0 0 8823.986
## 597 42 0 29.480 2 0 1 0 7640.309
## 598 34 0 33.250 1 0 0 0 5594.846
## 599 43 1 32.600 2 0 0 1 7441.501
## 600 52 0 37.525 2 1 0 0 33471.972
## 601 18 0 39.160 0 0 1 0 1633.044
## 602 51 1 31.635 0 1 0 0 9174.136
## 603 56 0 25.300 0 0 0 1 11070.535
## 604 64 0 39.050 3 0 1 0 16085.128
## 605 19 0 28.310 0 1 0 0 17468.984
## 606 51 0 34.100 0 0 1 0 9283.562
## 607 27 0 25.175 0 0 0 0 3558.620
## 608 59 0 23.655 0 1 0 0 25678.778
## 609 28 1 26.980 2 0 0 0 4435.094
## 610 30 1 37.800 2 0 0 1 39241.442
## 611 47 0 29.370 1 0 1 0 8547.691
## 612 38 0 34.800 2 0 0 1 6571.544
## 613 18 0 33.155 0 0 0 0 2207.697
## 614 34 0 19.000 3 0 0 0 6753.038
## 615 20 0 33.000 0 0 1 0 1880.070
## 616 47 0 36.630 1 0 1 0 42969.853
## 617 56 0 28.595 0 0 0 0 11658.115
## 618 49 1 25.600 2 0 0 1 23306.547
## 619 19 0 33.110 0 0 1 0 34439.856
## 620 55 0 37.100 0 0 0 1 10713.644
## 621 30 1 31.400 1 0 0 1 3659.346
## 622 37 1 34.100 4 0 0 1 40182.246
## 623 49 0 21.300 1 0 0 1 9182.170
## 624 18 1 33.535 0 0 0 0 34617.841
## 625 59 1 28.785 0 1 0 0 12129.614
## 626 29 0 26.030 0 1 0 0 3736.465
## 627 36 1 28.880 3 0 0 0 6748.591
## 628 33 1 42.460 1 0 1 0 11326.715
## 629 58 1 38.000 0 0 0 1 11365.952
## 630 44 0 38.950 0 1 0 0 42983.459
## 631 53 1 36.100 1 0 0 1 10085.846
## 632 24 1 29.300 0 0 0 1 1977.815
## 633 29 0 35.530 0 0 1 0 3366.670
## 634 40 1 22.705 2 0 0 0 7173.360
## 635 51 1 39.700 1 0 0 1 9391.346
## 636 64 1 38.190 0 0 0 0 14410.932
## 637 19 0 24.510 1 1 0 0 2709.112
## 638 35 0 38.095 2 0 0 0 24915.046
## 639 39 1 26.410 0 0 0 0 20149.323
## 640 56 1 33.660 4 0 1 0 12949.155
## 641 33 1 42.400 5 0 0 1 6666.243
## 642 42 1 28.310 3 1 0 0 32787.459
## 643 61 1 33.915 0 0 0 0 13143.865
## 644 23 0 34.960 3 1 0 0 4466.621
## 645 43 1 35.310 2 0 1 0 18806.145
## 646 48 1 30.780 3 0 0 0 10141.136
## 647 39 1 26.220 1 1 0 0 6123.569
## 648 40 0 23.370 3 0 0 0 8252.284
## 649 18 1 28.500 0 0 0 0 1712.227
## 650 58 0 32.965 0 0 0 0 12430.953
## 651 49 0 42.680 2 0 1 0 9800.888
## 652 53 0 39.600 1 0 1 0 10579.711
## 653 48 0 31.130 0 0 1 0 8280.623
## 654 45 0 36.300 2 0 1 0 8527.532
## 655 59 0 35.200 0 0 1 0 12244.531
## 656 52 0 25.300 2 0 1 0 24667.419
## 657 26 0 42.400 1 0 0 1 3410.324
## 658 27 1 33.155 2 1 0 0 4058.712
## 659 48 0 35.910 1 0 0 0 26392.260
## 660 57 0 28.785 4 0 0 0 14394.398
## 661 37 1 46.530 3 0 1 0 6435.624
## 662 57 0 23.980 1 0 1 0 22192.437
## 663 32 0 31.540 1 0 0 0 5148.553
## 664 18 1 33.660 0 0 1 0 1136.399
## 665 64 0 22.990 0 0 1 0 27037.914
## 666 43 1 38.060 2 0 1 0 42560.430
## 667 49 1 28.700 1 0 0 1 8703.456
## 668 40 0 32.775 2 1 0 0 40003.332
## 669 62 1 32.015 0 0 0 0 45710.208
## 670 40 0 29.810 1 0 1 0 6500.236
## 671 30 1 31.570 3 0 1 0 4837.582
## 672 29 0 31.160 0 0 0 0 3943.595
## 673 36 1 29.700 0 0 1 0 4399.731
## 674 41 0 31.020 0 0 1 0 6185.321
## 675 44 0 43.890 2 0 1 0 46200.985
## 676 45 1 21.375 0 1 0 0 7222.786
## 677 55 0 40.810 3 0 1 0 12485.801
## 678 60 1 31.350 3 1 0 0 46130.526
## 679 56 1 36.100 3 0 0 1 12363.547
## 680 49 0 23.180 2 1 0 0 10156.783
## 681 21 0 17.400 1 0 0 1 2585.269
## 682 19 1 20.300 0 0 0 1 1242.260
## 683 39 1 35.300 2 0 0 1 40103.890
## 684 53 1 24.320 0 1 0 0 9863.472
## 685 33 0 18.500 1 0 0 1 4766.022
## 686 53 1 26.410 2 0 0 0 11244.377
## 687 42 1 26.125 2 0 0 0 7729.646
## 688 40 1 41.690 0 0 1 0 5438.749
## 689 47 0 24.100 1 0 0 1 26236.580
## 690 27 1 31.130 1 0 1 0 34806.468
## 691 21 1 27.360 0 0 0 0 2104.113
## 692 47 1 36.200 1 0 0 1 8068.185
## 693 20 1 32.395 1 1 0 0 2362.229
## 694 24 1 23.655 0 1 0 0 2352.968
## 695 27 0 34.800 1 0 0 1 3577.999
## 696 26 0 40.185 0 1 0 0 3201.245
## 697 53 0 32.300 2 0 0 0 29186.482
## 698 41 1 35.750 1 0 1 0 40273.645
## 699 56 1 33.725 0 1 0 0 10976.246
## 700 23 0 39.270 2 0 1 0 3500.612
## 701 21 0 34.870 0 0 1 0 2020.552
## 702 50 0 44.745 0 0 0 0 9541.696
## 703 53 1 41.470 0 0 1 0 9504.310
## 704 34 0 26.410 1 1 0 0 5385.338
## 705 47 0 29.545 1 1 0 0 8930.935
## 706 33 0 32.900 2 0 0 1 5375.038
## 707 51 0 38.060 0 0 1 0 44400.406
## 708 49 1 28.690 3 1 0 0 10264.442
## 709 31 0 30.495 3 0 0 0 6113.231
## 710 36 0 27.740 0 0 0 0 5469.007
## 711 18 1 35.200 1 0 1 0 1727.540
## 712 50 0 23.540 2 0 1 0 10107.221
## 713 43 0 30.685 2 1 0 0 8310.839
## 714 20 1 40.470 0 0 0 0 1984.453
## 715 24 0 22.600 0 0 0 1 2457.502
## 716 60 1 28.900 0 0 0 1 12146.971
## 717 49 0 22.610 1 1 0 0 9566.991
## 718 60 1 24.320 1 1 0 0 13112.605
## 719 51 0 36.670 2 1 0 0 10848.134
## 720 58 0 33.440 0 1 0 0 12231.614
## 721 51 0 40.660 0 0 0 0 9875.680
## 722 53 1 36.600 3 0 0 1 11264.541
## 723 62 1 37.400 0 0 0 1 12979.358
## 724 19 1 35.400 0 0 0 1 1263.249
## 725 50 0 27.075 1 0 0 0 10106.134
## 726 30 0 39.050 3 0 1 0 40932.429
## 727 41 1 28.405 1 1 0 0 6664.686
## 728 29 0 21.755 1 0 0 0 16657.717
## 729 18 0 40.280 0 0 0 0 2217.601
## 730 41 0 36.080 1 0 1 0 6781.354
## 731 35 1 24.420 3 0 1 0 19361.999
## 732 53 1 21.400 1 0 0 1 10065.413
## 733 24 0 30.100 3 0 0 1 4234.927
## 734 48 0 27.265 1 0 0 0 9447.250
## 735 59 0 32.100 3 0 0 1 14007.222
## 736 49 0 34.770 1 1 0 0 9583.893
## 737 37 0 38.390 0 0 1 0 40419.019
## 738 26 1 23.700 2 0 0 1 3484.331
## 739 23 1 31.730 3 0 0 0 36189.102
## 740 29 1 35.500 2 0 0 1 44585.456
## 741 45 1 24.035 2 0 0 0 8604.484
## 742 27 1 29.150 0 0 1 0 18246.496
## 743 53 1 34.105 0 0 0 0 43254.418
## 744 31 0 26.620 0 0 1 0 3757.845
## 745 50 1 26.410 0 1 0 0 8827.210
## 746 50 0 30.115 1 1 0 0 9910.360
## 747 34 1 27.000 2 0 0 1 11737.849
## 748 19 1 21.755 0 1 0 0 1627.282
## 749 47 0 36.000 1 0 0 1 8556.907
## 750 28 1 30.875 0 1 0 0 3062.508
## 751 37 0 26.400 0 0 1 0 19539.243
## 752 21 1 28.975 0 1 0 0 1906.358
## 753 64 1 37.905 0 1 0 0 14210.536
## 754 58 0 22.770 0 0 1 0 11833.782
## 755 24 1 33.630 4 0 0 0 17128.426
## 756 31 1 27.645 2 0 0 0 5031.270
## 757 39 0 22.800 3 0 0 0 7985.815
## 758 47 0 27.830 0 0 1 0 23065.421
## 759 30 1 37.430 3 0 0 0 5428.728
## 760 18 1 38.170 0 0 1 0 36307.798
## 761 22 0 34.580 2 0 0 0 3925.758
## 762 23 1 35.200 1 0 0 1 2416.955
## 763 33 1 27.100 1 0 0 1 19040.876
## 764 27 1 26.030 0 0 0 0 3070.809
## 765 45 0 25.175 2 0 0 0 9095.068
## 766 57 0 31.825 0 1 0 0 11842.624
## 767 47 1 32.300 1 0 0 1 8062.764
## 768 42 0 29.000 1 0 0 1 7050.642
## 769 64 0 39.700 0 0 0 1 14319.031
## 770 38 0 19.475 2 1 0 0 6933.242
## 771 61 1 36.100 3 0 0 1 27941.288
## 772 53 0 26.700 2 0 0 1 11150.780
## 773 44 0 36.480 0 0 0 0 12797.210
## 774 19 0 28.880 0 1 0 0 17748.506
## 775 41 1 34.200 2 1 0 0 7261.741
## 776 51 1 33.330 3 0 1 0 10560.492
## 777 40 1 32.300 2 1 0 0 6986.697
## 778 45 1 39.805 0 0 0 0 7448.404
## 779 35 1 34.320 3 0 1 0 5934.380
## 780 53 1 28.880 0 1 0 0 9869.810
## 781 30 1 24.400 3 0 0 1 18259.216
## 782 18 1 41.140 0 0 1 0 1146.797
## 783 51 1 35.970 1 0 1 0 9386.161
## 784 50 0 27.600 1 0 0 1 24520.264
## 785 31 0 29.260 1 0 1 0 4350.514
## 786 35 0 27.700 3 0 0 1 6414.178
## 787 60 1 36.955 0 0 0 0 12741.167
## 788 21 1 36.860 0 1 0 0 1917.318
## 789 29 1 22.515 3 0 0 0 5209.579
## 790 62 0 29.920 0 0 1 0 13457.961
## 791 39 0 41.800 0 0 1 0 5662.225
## 792 19 1 27.600 0 0 0 1 1252.407
## 793 22 0 23.180 0 0 0 0 2731.912
## 794 53 1 20.900 0 0 1 0 21195.818
## 795 39 0 31.920 2 1 0 0 7209.492
## 796 27 1 28.500 0 1 0 0 18310.742
## 797 30 1 44.220 2 0 1 0 4266.166
## 798 30 0 22.895 1 0 0 0 4719.524
## 799 58 0 33.100 0 0 0 1 11848.141
## 800 33 1 24.795 0 0 0 0 17904.527
## 801 42 0 26.180 1 0 1 0 7046.722
## 802 64 0 35.970 0 0 1 0 14313.846
## 803 21 1 22.300 1 0 0 1 2103.080
## 804 18 0 42.240 0 0 1 0 38792.686
## 805 23 1 26.510 0 0 1 0 1815.876
## 806 45 0 35.815 0 1 0 0 7731.858
## 807 40 0 41.420 1 1 0 0 28476.735
## 808 19 0 36.575 0 1 0 0 2136.882
## 809 18 1 30.140 0 0 1 0 1131.507
## 810 25 1 25.840 1 0 0 0 3309.793
## 811 46 0 30.800 3 0 0 1 9414.920
## 812 33 0 42.940 3 1 0 0 6360.994
## 813 54 1 21.010 2 0 1 0 11013.712
## 814 28 1 22.515 2 0 0 0 4428.888
## 815 36 1 34.430 2 0 1 0 5584.306
## 816 20 0 31.460 0 0 1 0 1877.929
## 817 24 0 24.225 0 1 0 0 2842.761
## 818 23 1 37.100 3 0 0 1 3597.596
## 819 47 0 26.125 1 0 0 0 23401.306
## 820 33 0 35.530 0 1 0 0 55135.402
## 821 45 1 33.700 1 0 0 1 7445.918
## 822 26 1 17.670 0 1 0 0 2680.949
## 823 18 0 31.130 0 0 1 0 1621.883
## 824 44 0 29.810 2 0 1 0 8219.204
## 825 60 1 24.320 0 1 0 0 12523.605
## 826 64 0 31.825 2 0 0 0 16069.085
## 827 56 1 31.790 2 0 1 0 43813.866
## 828 36 1 28.025 1 0 0 0 20773.628
## 829 41 1 30.780 3 0 0 0 39597.407
## 830 39 1 21.850 1 1 0 0 6117.494
## 831 63 1 33.100 0 0 0 1 13393.756
## 832 36 0 25.840 0 1 0 0 5266.366
## 833 28 0 23.845 2 1 0 0 4719.737
## 834 58 1 34.390 0 1 0 0 11743.934
## 835 36 1 33.820 1 1 0 0 5377.458
## 836 42 1 35.970 2 0 1 0 7160.330
## 837 36 1 31.500 0 0 0 1 4402.233
## 838 56 0 28.310 0 0 0 0 11657.719
## 839 35 0 23.465 2 0 0 0 6402.291
## 840 59 0 31.350 0 1 0 0 12622.180
## 841 21 1 31.100 0 0 0 1 1526.312
## 842 59 1 24.700 0 0 0 0 12323.936
## 843 23 0 32.780 2 0 1 0 36021.011
## 844 57 0 29.810 0 0 1 0 27533.913
## 845 53 1 30.495 0 0 0 0 10072.055
## 846 60 0 32.450 0 0 1 0 45008.955
## 847 51 0 34.200 1 0 0 1 9872.701
## 848 23 1 50.380 1 0 1 0 2438.055
## 849 27 0 24.100 0 0 0 1 2974.126
## 850 55 1 32.775 0 1 0 0 10601.632
## 851 37 0 30.780 0 0 0 0 37270.151
## 852 61 1 32.300 2 1 0 0 14119.620
## 853 46 0 35.530 0 0 0 0 42111.665
## 854 53 0 23.750 2 0 0 0 11729.680
## 855 49 0 23.845 3 0 0 0 24106.913
## 856 20 0 29.600 0 0 0 1 1875.344
## 857 48 0 33.110 0 0 1 0 40974.165
## 858 25 1 24.130 0 1 0 0 15817.986
## 859 25 0 32.230 1 0 1 0 18218.161
## 860 57 1 28.100 0 0 0 1 10965.446
## 861 37 0 47.600 2 0 0 1 46113.511
## 862 38 0 28.000 3 0 0 1 7151.092
## 863 55 0 33.535 2 1 0 0 12269.689
## 864 36 0 19.855 0 0 0 0 5458.046
## 865 51 1 25.400 0 0 0 1 8782.469
## 866 40 1 29.900 2 0 0 1 6600.361
## 867 18 1 37.290 0 0 1 0 1141.445
## 868 57 1 43.700 1 0 0 1 11576.130
## 869 61 1 23.655 0 0 0 0 13129.603
## 870 25 0 24.300 3 0 0 1 4391.652
## 871 50 1 36.200 0 0 0 1 8457.818
## 872 26 0 29.480 1 0 1 0 3392.365
## 873 42 1 24.860 0 0 1 0 5966.887
## 874 43 1 30.100 1 0 0 1 6849.026
## 875 44 1 21.850 3 0 0 0 8891.139
## 876 23 0 28.120 0 1 0 0 2690.114
## 877 49 0 27.100 1 0 0 1 26140.360
## 878 33 1 33.440 5 0 1 0 6653.789
## 879 41 1 28.800 1 0 0 1 6282.235
## 880 37 0 29.500 2 0 0 1 6311.952
## 881 22 1 34.800 3 0 0 1 3443.064
## 882 23 1 27.360 1 1 0 0 2789.057
## 883 21 0 22.135 0 0 0 0 2585.851
## 884 51 0 37.050 3 0 0 0 46255.113
## 885 25 1 26.695 4 1 0 0 4877.981
## 886 32 1 28.930 1 0 1 0 19719.695
## 887 57 1 28.975 0 0 0 0 27218.437
## 888 36 0 30.020 0 1 0 0 5272.176
## 889 22 1 39.500 0 0 0 1 1682.597
## 890 57 1 33.630 1 1 0 0 11945.133
## 891 64 0 26.885 0 1 0 0 29330.983
## 892 36 0 29.040 4 0 1 0 7243.814
## 893 54 1 24.035 0 0 0 0 10422.917
## 894 47 1 38.940 2 0 1 0 44202.654
## 895 62 1 32.110 0 0 0 0 13555.005
## 896 61 0 44.000 0 0 0 1 13063.883
## 897 43 0 20.045 2 0 0 0 19798.055
## 898 19 1 25.555 1 1 0 0 2221.564
## 899 18 0 40.260 0 0 1 0 1634.573
## 900 19 0 22.515 0 1 0 0 2117.339
## 901 49 1 22.515 0 0 0 0 8688.859
## 902 60 1 40.920 0 0 1 0 48673.559
## 903 26 1 27.265 3 0 0 0 4661.286
## 904 49 1 36.850 0 0 1 0 8125.784
## 905 60 0 35.100 0 0 0 1 12644.589
## 906 26 0 29.355 2 0 0 0 4564.191
## 907 27 1 32.585 3 0 0 0 4846.920
## 908 44 0 32.340 1 0 1 0 7633.721
## 909 63 1 39.800 3 0 0 1 15170.069
## 910 32 0 24.600 0 0 0 1 17496.306
## 911 22 1 28.310 1 1 0 0 2639.043
## 912 18 1 31.730 0 0 0 0 33732.687
## 913 59 0 26.695 3 1 0 0 14382.709
## 914 44 0 27.500 1 0 0 1 7626.993
## 915 33 1 24.605 2 1 0 0 5257.508
## 916 24 0 33.990 0 0 1 0 2473.334
## 917 43 0 26.885 0 1 0 0 21774.322
## 918 45 1 22.895 0 0 0 0 35069.375
## 919 61 0 28.200 0 0 0 1 13041.921
## 920 35 0 34.210 1 0 1 0 5245.227
## 921 62 0 25.000 0 0 0 1 13451.122
## 922 62 0 33.200 0 0 0 1 13462.520
## 923 38 1 31.000 1 0 0 1 5488.262
## 924 34 1 35.815 0 1 0 0 4320.411
## 925 43 1 23.200 0 0 0 1 6250.435
## 926 50 1 32.110 2 0 0 0 25333.333
## 927 19 0 23.400 2 0 0 1 2913.569
## 928 57 0 20.100 1 0 0 1 12032.326
## 929 62 0 39.160 0 0 1 0 13470.804
## 930 41 1 34.210 1 0 1 0 6289.755
## 931 26 1 46.530 1 0 1 0 2927.065
## 932 39 0 32.500 1 0 0 1 6238.298
## 933 46 1 25.800 5 0 0 1 10096.970
## 934 45 0 35.300 0 0 0 1 7348.142
## 935 32 1 37.180 2 0 1 0 4673.392
## 936 59 0 27.500 0 0 0 1 12233.828
## 937 44 1 29.735 2 0 0 0 32108.663
## 938 39 0 24.225 5 1 0 0 8965.796
## 939 18 1 26.180 2 0 1 0 2304.002
## 940 53 1 29.480 0 0 1 0 9487.644
## 941 18 1 23.210 0 0 1 0 1121.874
## 942 50 0 46.090 1 0 1 0 9549.565
## 943 18 0 40.185 0 0 0 0 2217.469
## 944 19 1 22.610 0 1 0 0 1628.471
## 945 62 1 39.930 0 0 1 0 12982.875
## 946 56 0 35.800 1 0 0 1 11674.130
## 947 42 1 35.800 2 0 0 1 7160.094
## 948 37 1 34.200 1 0 0 0 39047.285
## 949 42 1 31.255 0 1 0 0 6358.776
## 950 25 1 29.700 3 0 0 1 19933.458
## 951 57 1 18.335 0 0 0 0 11534.873
## 952 51 1 42.900 2 0 1 0 47462.894
## 953 30 0 28.405 1 1 0 0 4527.183
## 954 44 1 30.200 2 0 0 1 38998.546
## 955 34 1 27.835 1 1 0 0 20009.634
## 956 31 1 39.490 1 0 1 0 3875.734
## 957 54 1 30.800 1 0 1 0 41999.520
## 958 24 1 26.790 1 1 0 0 12609.887
## 959 43 1 34.960 1 0 0 0 41034.221
## 960 48 1 36.670 1 1 0 0 28468.919
## 961 19 0 39.615 1 1 0 0 2730.108
## 962 29 0 25.900 0 0 0 1 3353.284
## 963 63 0 35.200 1 0 1 0 14474.675
## 964 46 1 24.795 3 0 0 0 9500.573
## 965 52 1 36.765 2 1 0 0 26467.097
## 966 35 1 27.100 1 0 0 1 4746.344
## 967 51 1 24.795 2 1 0 0 23967.383
## 968 44 1 25.365 1 1 0 0 7518.025
## 969 21 1 25.745 2 0 0 0 3279.869
## 970 39 0 34.320 5 0 1 0 8596.828
## 971 50 0 28.160 3 0 1 0 10702.642
## 972 34 0 23.560 0 0 0 0 4992.376
## 973 22 0 20.235 0 1 0 0 2527.819
## 974 19 0 40.500 0 0 0 1 1759.338
## 975 26 1 35.420 0 0 1 0 2322.622
## 976 29 1 22.895 0 0 0 0 16138.762
## 977 48 1 40.150 0 0 1 0 7804.160
## 978 26 1 29.150 1 0 1 0 2902.907
## 979 45 0 39.995 3 0 0 0 9704.668
## 980 36 0 29.920 0 0 1 0 4889.037
## 981 54 1 25.460 1 0 0 0 25517.114
## 982 34 1 21.375 0 0 0 0 4500.339
## 983 31 1 25.900 3 0 0 1 19199.944
## 984 27 0 30.590 1 0 0 0 16796.412
## 985 20 1 30.115 5 0 0 0 4915.060
## 986 44 0 25.800 1 0 0 1 7624.630
## 987 43 1 30.115 3 1 0 0 8410.047
## 988 45 0 27.645 1 1 0 0 28340.189
## 989 34 1 34.675 0 0 0 0 4518.826
## 990 24 0 20.520 0 0 0 0 14571.891
## 991 26 0 19.800 1 0 0 1 3378.910
## 992 38 0 27.835 2 0 0 0 7144.863
## 993 50 0 31.600 2 0 0 1 10118.424
## 994 38 1 28.270 1 0 1 0 5484.467
## 995 27 0 20.045 3 1 0 0 16420.495
## 996 39 0 23.275 3 0 0 0 7986.475
## 997 39 0 34.100 3 0 0 1 7418.522
## 998 63 0 36.850 0 0 1 0 13887.969
## 999 33 0 36.290 3 0 0 0 6551.750
## 1000 36 0 26.885 0 1 0 0 5267.818
## 1001 30 1 22.990 2 1 0 0 17361.766
## 1002 24 1 32.700 0 0 0 1 34472.841
## 1003 24 1 25.800 0 0 0 1 1972.950
## 1004 48 1 29.600 0 0 0 1 21232.182
## 1005 47 1 19.190 1 0 0 0 8627.541
## 1006 29 1 31.730 2 1 0 0 4433.388
## 1007 28 1 29.260 2 0 0 0 4438.263
## 1008 47 1 28.215 3 1 0 0 24915.221
## 1009 25 1 24.985 2 0 0 0 23241.475
## 1010 51 1 27.740 1 0 0 0 9957.722
## 1011 48 0 22.800 0 0 0 1 8269.044
## 1012 43 1 20.130 2 0 1 0 18767.738
## 1013 61 0 33.330 4 0 1 0 36580.282
## 1014 48 1 32.300 1 1 0 0 8765.249
## 1015 38 0 27.600 0 0 0 1 5383.536
## 1016 59 1 25.460 0 1 0 0 12124.992
## 1017 19 0 24.605 1 1 0 0 2709.244
## 1018 26 0 34.200 2 0 0 1 3987.926
## 1019 54 0 35.815 3 1 0 0 12495.291
## 1020 21 0 32.680 2 1 0 0 26018.951
## 1021 51 1 37.000 0 0 0 1 8798.593
## 1022 22 0 31.020 3 0 1 0 35595.590
## 1023 47 1 36.080 1 0 1 0 42211.138
## 1024 18 1 23.320 1 0 1 0 1711.027
## 1025 47 0 45.320 1 0 1 0 8569.862
## 1026 21 0 34.600 0 0 0 1 2020.177
## 1027 19 1 26.030 1 1 0 0 16450.895
## 1028 23 1 18.715 0 1 0 0 21595.382
## 1029 54 1 31.600 0 0 0 1 9850.432
## 1030 37 0 17.290 2 0 0 0 6877.980
## 1031 46 0 23.655 1 1 0 0 21677.283
## 1032 55 0 35.200 0 0 1 0 44423.803
## 1033 30 0 27.930 0 0 0 0 4137.523
## 1034 18 1 21.565 0 0 0 0 13747.872
## 1035 61 1 38.380 0 1 0 0 12950.071
## 1036 54 0 23.000 3 0 0 1 12094.478
## 1037 22 1 37.070 2 0 1 0 37484.449
## 1038 45 0 30.495 1 1 0 0 39725.518
## 1039 22 1 28.880 0 0 0 0 2250.835
## 1040 19 1 27.265 2 1 0 0 22493.660
## 1041 35 0 28.025 0 1 0 0 20234.855
## 1042 18 1 23.085 0 0 0 0 1704.700
## 1043 20 1 30.685 0 0 0 0 33475.817
## 1044 28 0 25.800 0 0 0 1 3161.454
## 1045 55 1 35.245 1 0 0 0 11394.066
## 1046 43 0 24.700 2 1 0 0 21880.820
## 1047 43 0 25.080 0 0 0 0 7325.048
## 1048 22 1 52.580 1 0 1 0 44501.398
## 1049 25 0 22.515 1 1 0 0 3594.171
## 1050 49 1 30.900 0 0 0 1 39727.614
## 1051 44 0 36.955 1 1 0 0 8023.135
## 1052 64 1 26.410 0 0 0 0 14394.558
## 1053 49 1 29.830 1 0 0 0 9288.027
## 1054 47 1 29.800 3 0 0 1 25309.489
## 1055 27 0 21.470 0 1 0 0 3353.470
## 1056 55 1 27.645 0 1 0 0 10594.502
## 1057 48 0 28.900 0 0 0 1 8277.523
## 1058 45 0 31.790 0 0 1 0 17929.303
## 1059 24 0 39.490 0 0 1 0 2480.979
## 1060 32 1 33.820 1 1 0 0 4462.722
## 1061 24 1 32.010 0 0 1 0 1981.582
## 1062 57 1 27.940 1 0 1 0 11554.224
## 1063 59 1 41.140 1 0 1 0 48970.248
## 1064 36 1 28.595 3 1 0 0 6548.195
## 1065 29 0 25.600 4 0 0 1 5708.867
## 1066 42 0 25.300 1 0 0 1 7045.499
## 1067 48 1 37.290 2 0 1 0 8978.185
## 1068 39 1 42.655 0 0 0 0 5757.413
## 1069 63 1 21.660 1 1 0 0 14349.854
## 1070 54 0 31.900 1 0 1 0 10928.849
## 1071 37 1 37.070 1 0 1 0 39871.704
## 1072 63 1 31.445 0 0 0 0 13974.456
## 1073 21 1 31.255 0 1 0 0 1909.527
## 1074 54 0 28.880 2 0 0 0 12096.651
## 1075 60 0 18.335 0 0 0 0 13204.286
## 1076 32 0 29.590 1 0 1 0 4562.842
## 1077 47 0 32.000 1 0 0 1 8551.347
## 1078 21 1 26.030 0 0 0 0 2102.265
## 1079 28 1 31.680 0 0 1 0 34672.147
## 1080 63 1 33.660 3 0 1 0 15161.534
## 1081 18 1 21.780 2 0 1 0 11884.049
## 1082 32 1 27.835 1 1 0 0 4454.403
## 1083 38 1 19.950 1 1 0 0 5855.903
## 1084 32 1 31.500 1 0 0 1 4076.497
## 1085 62 0 30.495 2 1 0 0 15019.760
## 1086 39 0 18.300 5 0 0 1 19023.260
## 1087 55 1 28.975 0 0 0 0 10796.350
## 1088 57 1 31.540 0 1 0 0 11353.228
## 1089 52 1 47.740 1 0 1 0 9748.911
## 1090 56 1 22.100 0 0 0 1 10577.087
## 1091 47 1 36.190 0 0 1 0 41676.081
## 1092 55 0 29.830 0 0 0 0 11286.539
## 1093 23 1 32.700 3 0 0 1 3591.480
## 1094 22 0 30.400 0 1 0 0 33907.548
## 1095 50 0 33.700 4 0 0 1 11299.343
## 1096 18 0 31.350 4 0 0 0 4561.189
## 1097 51 0 34.960 2 0 0 0 44641.197
## 1098 22 1 33.770 0 0 1 0 1674.632
## 1099 52 0 30.875 0 0 0 0 23045.566
## 1100 25 0 33.990 1 0 1 0 3227.121
## 1101 33 0 19.095 2 0 0 0 16776.304
## 1102 53 1 28.600 3 0 0 1 11253.421
## 1103 29 1 38.940 1 0 1 0 3471.410
## 1104 58 1 36.080 0 0 1 0 11363.283
## 1105 37 1 29.800 0 0 0 1 20420.605
## 1106 54 0 31.240 0 0 1 0 10338.932
## 1107 49 0 29.925 0 1 0 0 8988.159
## 1108 50 0 26.220 2 1 0 0 10493.946
## 1109 26 1 30.000 1 0 0 1 2904.088
## 1110 45 1 20.350 3 0 1 0 8605.362
## 1111 54 0 32.300 1 0 0 0 11512.405
## 1112 38 1 38.390 3 0 1 0 41949.244
## 1113 48 0 25.850 3 0 1 0 24180.933
## 1114 28 0 26.315 3 1 0 0 5312.170
## 1115 23 1 24.510 0 0 0 0 2396.096
## 1116 55 1 32.670 1 0 1 0 10807.486
## 1117 41 1 29.640 5 0 0 0 9222.403
## 1118 25 1 33.330 2 0 1 0 36124.574
## 1119 33 1 35.750 1 0 1 0 38282.749
## 1120 30 0 19.950 3 1 0 0 5693.431
## 1121 23 0 31.400 0 0 0 1 34166.273
## 1122 46 1 38.170 2 0 1 0 8347.164
## 1123 53 0 36.860 3 1 0 0 46661.442
## 1124 27 0 32.395 1 0 0 0 18903.491
## 1125 23 0 42.750 1 0 0 0 40904.200
## 1126 63 0 25.080 0 1 0 0 14254.608
## 1127 55 1 29.900 0 0 0 1 10214.636
## 1128 35 0 35.860 2 0 1 0 5836.520
## 1129 34 1 32.800 1 0 0 1 14358.364
## 1130 19 0 18.600 0 0 0 1 1728.897
## 1131 39 0 23.870 5 0 1 0 8582.302
## 1132 27 1 45.900 2 0 0 1 3693.428
## 1133 57 1 40.280 0 0 0 0 20709.020
## 1134 52 0 18.335 0 1 0 0 9991.038
## 1135 28 1 33.820 0 1 0 0 19673.336
## 1136 50 0 28.120 3 1 0 0 11085.587
## 1137 44 0 25.000 1 0 0 1 7623.518
## 1138 26 0 22.230 0 1 0 0 3176.288
## 1139 33 1 30.250 0 0 1 0 3704.354
## 1140 19 0 32.490 0 1 0 0 36898.733
## 1141 50 1 37.070 1 0 1 0 9048.027
## 1142 41 0 32.600 3 0 0 1 7954.517
## 1143 52 0 24.860 0 0 1 0 27117.994
## 1144 39 1 32.340 2 0 1 0 6338.076
## 1145 50 1 32.300 2 0 0 1 9630.397
## 1146 52 1 32.775 3 1 0 0 11289.109
## 1147 60 1 32.800 0 0 0 1 52590.829
## 1148 20 0 31.920 0 1 0 0 2261.569
## 1149 55 1 21.500 1 0 0 1 10791.960
## 1150 42 1 34.100 0 0 0 1 5979.731
## 1151 18 0 30.305 0 0 0 0 2203.736
## 1152 58 0 36.480 0 1 0 0 12235.839
## 1153 43 0 32.560 3 0 1 0 40941.285
## 1154 35 0 35.815 1 1 0 0 5630.458
## 1155 48 0 27.930 4 1 0 0 11015.175
## 1156 36 0 22.135 3 0 0 0 7228.216
## 1157 19 1 44.880 0 0 1 0 39722.746
## 1158 23 0 23.180 2 1 0 0 14426.074
## 1159 20 0 30.590 0 0 0 0 2459.720
## 1160 32 0 41.100 0 0 0 1 3989.841
## 1161 43 0 34.580 1 1 0 0 7727.253
## 1162 34 1 42.130 2 0 1 0 5124.189
## 1163 30 1 38.830 1 0 1 0 18963.172
## 1164 18 0 28.215 0 0 0 0 2200.831
## 1165 41 0 28.310 1 1 0 0 7153.554
## 1166 35 0 26.125 0 0 0 0 5227.989
## 1167 57 1 40.370 0 0 1 0 10982.501
## 1168 29 0 24.600 2 0 0 1 4529.477
## 1169 32 1 35.200 2 0 0 1 4670.640
## 1170 37 0 34.105 1 1 0 0 6112.353
## 1171 18 1 27.360 1 0 0 0 17178.682
## 1172 43 0 26.700 2 0 0 1 22478.600
## 1173 56 0 41.910 0 0 1 0 11093.623
## 1174 38 1 29.260 2 1 0 0 6457.843
## 1175 29 1 32.110 2 1 0 0 4433.916
## 1176 22 0 27.100 0 0 0 1 2154.361
## 1177 52 0 24.130 1 1 0 0 23887.663
## 1178 40 0 27.400 1 0 0 1 6496.886
## 1179 23 0 34.865 0 0 0 0 2899.489
## 1180 31 1 29.810 0 0 1 0 19350.369
## 1181 42 0 41.325 1 0 0 0 7650.774
## 1182 24 0 29.925 0 1 0 0 2850.684
## 1183 25 0 30.300 0 0 0 1 2632.992
## 1184 48 0 27.360 1 0 0 0 9447.382
## 1185 23 0 28.490 1 0 1 0 18328.238
## 1186 45 1 23.560 2 0 0 0 8603.823
## 1187 20 1 35.625 3 1 0 0 37465.344
## 1188 62 0 32.680 0 1 0 0 13844.797
## 1189 43 0 25.270 1 0 0 0 21771.342
## 1190 23 0 28.000 0 0 0 1 13126.677
## 1191 31 0 32.775 2 1 0 0 5327.400
## 1192 41 0 21.755 1 0 0 0 13725.472
## 1193 58 0 32.395 1 0 0 0 13019.161
## 1194 48 0 36.575 0 1 0 0 8671.191
## 1195 31 0 21.755 0 1 0 0 4134.082
## 1196 19 0 27.930 3 1 0 0 18838.704
## 1197 19 0 30.020 0 1 0 0 33307.551
## 1198 41 1 33.550 0 0 1 0 5699.837
## 1199 40 1 29.355 1 1 0 0 6393.603
## 1200 31 0 25.800 2 0 0 1 4934.705
## 1201 37 1 24.320 2 1 0 0 6198.752
## 1202 46 1 40.375 2 1 0 0 8733.229
## 1203 22 1 32.110 0 1 0 0 2055.325
## 1204 51 1 32.300 1 0 0 0 9964.060
## 1205 18 0 27.280 3 0 1 0 18223.451
## 1206 35 1 17.860 1 1 0 0 5116.500
## 1207 59 0 34.800 2 0 0 1 36910.608
## 1208 36 1 33.400 2 0 0 1 38415.474
## 1209 37 0 25.555 1 0 0 0 20296.863
## 1210 59 1 37.100 1 0 0 1 12347.172
## 1211 36 1 30.875 1 1 0 0 5373.364
## 1212 39 1 34.100 2 0 1 0 23563.016
## 1213 18 1 21.470 0 0 0 0 1702.455
## 1214 52 0 33.300 2 0 0 1 10806.839
## 1215 27 0 31.255 1 1 0 0 3956.071
## 1216 18 1 39.140 0 0 0 0 12890.058
## 1217 40 1 25.080 0 0 1 0 5415.661
## 1218 29 1 37.290 2 0 1 0 4058.116
## 1219 46 0 34.600 1 0 0 1 41661.602
## 1220 38 0 30.210 3 1 0 0 7537.164
## 1221 30 0 21.945 1 0 0 0 4718.204
## 1222 40 1 24.970 2 0 1 0 6593.508
## 1223 50 1 25.300 0 0 1 0 8442.667
## 1224 20 0 24.420 0 0 1 0 26125.675
## 1225 41 1 23.940 1 0 0 0 6858.480
## 1226 33 0 39.820 1 0 1 0 4795.657
## 1227 38 1 16.815 2 0 0 0 6640.545
## 1228 42 1 37.180 2 0 1 0 7162.012
## 1229 56 1 34.430 0 0 1 0 10594.226
## 1230 58 1 30.305 0 0 0 0 11938.256
## 1231 52 1 34.485 3 1 0 0 60021.399
## 1232 20 0 21.800 0 0 0 1 20167.336
## 1233 54 0 24.605 3 1 0 0 12479.709
## 1234 58 1 23.300 0 0 0 1 11345.519
## 1235 45 0 27.830 2 0 1 0 8515.759
## 1236 26 1 31.065 0 1 0 0 2699.568
## 1237 63 0 21.660 0 0 0 0 14449.854
## 1238 58 0 28.215 0 1 0 0 12224.351
## 1239 37 1 22.705 3 0 0 0 6985.507
## 1240 25 0 42.130 1 0 1 0 3238.436
## 1241 52 1 41.800 2 0 1 0 47269.854
## 1242 64 1 36.960 2 0 1 0 49577.662
## 1243 22 0 21.280 3 1 0 0 4296.271
## 1244 28 0 33.110 0 0 1 0 3171.615
## 1245 18 1 33.330 0 0 1 0 1135.941
## 1246 28 1 24.300 5 0 0 1 5615.369
## 1247 45 0 25.700 3 0 0 1 9101.798
## 1248 33 1 29.400 4 0 0 1 6059.173
## 1249 18 0 39.820 0 0 1 0 1633.962
## 1250 32 1 33.630 1 0 0 0 37607.528
## 1251 24 1 29.830 0 0 0 0 18648.422
## 1252 19 1 19.800 0 0 0 1 1241.565
## 1253 20 1 27.300 0 0 0 1 16232.847
## 1254 40 0 29.300 4 0 0 1 15828.822
## 1255 34 0 27.720 0 0 1 0 4415.159
## 1256 42 0 37.900 0 0 0 1 6474.013
## 1257 51 0 36.385 3 1 0 0 11436.738
## 1258 54 0 27.645 1 1 0 0 11305.935
## 1259 55 1 37.715 3 1 0 0 30063.581
## 1260 52 0 23.180 0 0 0 0 10197.772
## 1261 32 0 20.520 0 0 0 0 4544.235
## 1262 28 1 37.100 1 0 0 1 3277.161
## 1263 41 0 28.050 1 0 1 0 6770.193
## 1264 43 0 29.900 1 0 0 1 7337.748
## 1265 49 0 33.345 2 0 0 0 10370.913
## 1266 64 1 23.760 0 0 1 0 26926.514
## 1267 55 0 30.500 0 0 0 1 10704.470
## 1268 24 1 31.065 0 0 0 0 34254.053
## 1269 20 0 33.300 0 0 0 1 1880.487
## 1270 45 1 27.500 3 0 0 1 8615.300
## 1271 26 1 33.915 1 1 0 0 3292.530
## 1272 25 0 34.485 0 1 0 0 3021.809
## 1273 43 1 25.520 5 0 1 0 14478.330
## 1274 35 1 27.610 1 0 1 0 4747.053
## 1275 26 1 27.060 0 0 1 0 17043.341
## 1276 57 1 23.700 0 0 0 1 10959.330
## 1277 22 0 30.400 0 0 0 0 2741.948
## 1278 32 0 29.735 0 1 0 0 4357.044
## 1279 39 1 29.925 1 0 0 0 22462.044
## 1280 25 0 26.790 2 1 0 0 4189.113
## 1281 48 0 33.330 0 0 1 0 8283.681
## 1282 47 0 27.645 2 1 0 0 24535.699
## 1283 18 0 21.660 0 0 0 0 14283.459
## 1284 18 1 30.030 1 0 1 0 1720.354
## 1285 61 1 36.300 1 0 0 1 47403.880
## 1286 47 0 24.320 0 0 0 0 8534.672
## 1287 28 0 17.290 0 0 0 0 3732.625
## 1288 36 0 25.900 1 0 0 1 5472.449
## 1289 20 1 39.400 2 0 0 1 38344.566
## 1290 44 1 34.320 1 0 1 0 7147.473
## 1291 38 0 19.950 2 0 0 0 7133.903
## 1292 19 1 34.900 0 0 0 1 34828.654
## 1293 21 1 23.210 0 0 1 0 1515.345
## 1294 46 1 25.745 3 1 0 0 9301.894
## 1295 58 1 25.175 0 0 0 0 11931.125
## 1296 20 1 22.000 1 0 0 1 1964.780
## 1297 18 1 26.125 0 0 0 0 1708.926
## 1298 28 0 26.510 2 0 1 0 4340.441
## 1299 33 1 27.455 2 1 0 0 5261.469
## 1300 19 0 25.745 1 1 0 0 2710.829
## 1301 45 1 30.360 0 0 1 0 62592.873
## 1302 62 1 30.875 3 1 0 0 46718.163
## 1303 25 0 20.800 1 0 0 1 3208.787
## 1304 43 1 27.800 0 0 0 1 37829.724
## 1305 42 1 24.605 2 0 0 0 21259.378
## 1306 24 0 27.720 0 0 1 0 2464.619
## 1307 29 0 21.850 0 0 0 0 16115.305
## 1308 32 1 28.120 4 1 0 0 21472.479
## 1309 25 0 30.200 0 0 0 1 33900.653
## 1310 41 1 32.200 2 0 0 1 6875.961
## 1311 42 1 26.315 1 1 0 0 6940.910
## 1312 33 0 26.695 0 1 0 0 4571.413
## 1313 34 1 42.900 1 0 0 1 4536.259
## 1314 19 0 34.700 2 0 0 1 36397.576
## 1315 30 0 23.655 3 1 0 0 18765.875
## 1316 18 1 28.310 1 0 0 0 11272.331
## 1317 19 0 20.600 0 0 0 1 1731.677
## 1318 18 1 53.130 0 0 1 0 1163.463
## 1319 35 1 39.710 4 0 0 0 19496.719
## 1320 39 0 26.315 2 1 0 0 7201.701
## 1321 31 1 31.065 3 1 0 0 5425.023
## 1322 62 1 26.695 0 0 0 0 28101.333
## 1323 62 1 38.830 0 0 1 0 12981.346
## 1324 42 0 40.370 2 0 1 0 43896.376
## 1325 31 1 25.935 1 1 0 0 4239.893
## 1326 61 1 33.535 0 0 0 0 13143.337
## 1327 42 0 32.870 0 0 0 0 7050.021
## 1328 51 1 30.030 1 0 1 0 9377.905
## 1329 23 0 24.225 2 0 0 0 22395.744
## 1330 52 1 38.600 2 0 0 1 10325.206
## 1331 57 0 25.740 2 0 1 0 12629.166
## 1332 23 0 33.400 0 0 0 1 10795.937
## 1333 52 0 44.700 3 0 0 1 11411.685
## 1334 50 1 30.970 3 1 0 0 10600.548
## 1335 18 0 31.920 0 0 0 0 2205.981
## 1336 18 0 36.850 0 0 1 0 1629.833
## 1337 21 0 25.800 0 0 0 1 2007.945
## 1338 61 0 29.070 0 1 0 0 29141.360
## bmi_c
## 1 -2.76339686
## 2 3.10660314
## 3 2.33660314
## 4 -7.95839686
## 5 -1.78339686
## 6 -4.92339686
## 7 2.77660314
## 8 -2.92339686
## 9 -0.83339686
## 10 -4.82339686
## 11 -4.44339686
## 12 -4.37339686
## 13 3.73660314
## 14 9.15660314
## 15 11.46660314
## 16 -6.06339686
## 17 0.11660314
## 18 -6.81839686
## 19 9.63660314
## 20 4.63660314
## 21 5.34160314
## 22 1.73660314
## 23 3.43660314
## 24 1.25660314
## 25 -2.63839686
## 26 -2.94339686
## 27 -7.57839686
## 28 2.11160314
## 29 -13.27839686
## 30 5.63660314
## 31 4.93660314
## 32 -4.34839686
## 33 -2.06339686
## 34 -2.35339686
## 35 5.73660314
## 36 -10.23839686
## 37 2.30160314
## 38 -9.86339686
## 39 6.00660314
## 40 9.23660314
## 41 -4.06339686
## 42 5.96660314
## 43 -8.88339686
## 44 0.13660314
## 45 6.38660314
## 46 6.63660314
## 47 8.00160314
## 48 4.10660314
## 49 -6.13339686
## 50 4.53660314
## 51 4.96160314
## 52 2.96660314
## 53 -2.66339686
## 54 3.76660314
## 55 -1.97339686
## 56 6.29160314
## 57 1.16160314
## 58 1.01660314
## 59 -7.78339686
## 60 6.67160314
## 61 -3.30339686
## 62 2.99660314
## 63 -5.96339686
## 64 -4.72839686
## 65 -8.24339686
## 66 -1.76339686
## 67 8.43660314
## 68 -4.34839686
## 69 5.52660314
## 70 -6.68339686
## 71 -5.91339686
## 72 -2.16339686
## 73 -2.56339686
## 74 1.34660314
## 75 -3.26339686
## 76 3.34660314
## 77 -1.07339686
## 78 4.86660314
## 79 9.14160314
## 80 2.30160314
## 81 -3.77839686
## 82 7.62160314
## 83 6.95660314
## 84 10.56660314
## 85 4.13660314
## 86 -7.76839686
## 87 0.49660314
## 88 -3.46339686
## 89 -2.92339686
## 90 -3.68339686
## 91 8.82660314
## 92 -5.86839686
## 93 -0.83339686
## 94 4.10660314
## 95 0.63660314
## 96 6.95660314
## 97 0.13660314
## 98 7.61660314
## 99 -10.71339686
## 100 -11.36339686
## 101 0.93660314
## 102 -5.20339686
## 103 -0.54839686
## 104 -0.74339686
## 105 -3.16339686
## 106 -2.63839686
## 107 -2.26339686
## 108 0.21160314
## 109 -2.72339686
## 110 4.42660314
## 111 2.96660314
## 112 -0.96339686
## 113 0.13660314
## 114 5.05660314
## 115 1.54160314
## 116 -2.06839686
## 117 18.39660314
## 118 -2.72339686
## 119 -3.49339686
## 120 -7.29339686
## 121 6.43660314
## 122 -6.91339686
## 123 -1.68839686
## 124 0.68660314
## 125 3.25160314
## 126 -1.87839686
## 127 -2.36339686
## 128 6.73660314
## 129 -12.89839686
## 130 4.03660314
## 131 -4.15839686
## 132 -8.62339686
## 133 5.23660314
## 134 -5.10839686
## 135 -1.87839686
## 136 -2.61339686
## 137 3.43660314
## 138 -5.48839686
## 139 1.23660314
## 140 5.33660314
## 141 -8.24339686
## 142 1.82660314
## 143 -5.36339686
## 144 -0.92839686
## 145 -1.97339686
## 146 8.16660314
## 147 -0.16839686
## 148 7.06660314
## 149 6.76660314
## 150 -2.26339686
## 151 -6.53339686
## 152 -0.96339686
## 153 6.48160314
## 154 -7.29339686
## 155 -5.20339686
## 156 8.85660314
## 157 -6.24339686
## 158 -5.48839686
## 159 4.86660314
## 160 -2.83339686
## 161 -4.06339686
## 162 6.18660314
## 163 8.93660314
## 164 -0.86339686
## 165 -1.02339686
## 166 -2.44839686
## 167 6.33660314
## 168 2.49160314
## 169 1.16160314
## 170 -11.75839686
## 171 10.80660314
## 172 -0.36339686
## 173 -14.70339686
## 174 4.13660314
## 175 2.68160314
## 176 7.03660314
## 177 -2.82839686
## 178 -1.46339686
## 179 -1.76339686
## 180 2.49160314
## 181 -2.06839686
## 182 7.61660314
## 183 -10.71339686
## 184 -4.25339686
## 185 0.02660314
## 186 11.23160314
## 187 -0.74339686
## 188 0.23660314
## 189 1.53660314
## 190 1.44660314
## 191 0.90660314
## 192 -4.46339686
## 193 -4.92339686
## 194 -4.06339686
## 195 3.76660314
## 196 -0.07339686
## 197 2.13660314
## 198 -2.06339686
## 199 -12.61339686
## 200 8.66660314
## 201 1.44660314
## 202 1.56660314
## 203 -6.62839686
## 204 5.41660314
## 205 -8.36339686
## 206 -1.78339686
## 207 -4.26339686
## 208 -2.92339686
## 209 1.13660314
## 210 10.56660314
## 211 2.33660314
## 212 0.21160314
## 213 -2.16339686
## 214 -3.93339686
## 215 0.23660314
## 216 6.43660314
## 217 -4.06339686
## 218 -7.56339686
## 219 -0.74339686
## 220 -7.45339686
## 221 3.03660314
## 222 2.58660314
## 223 0.13660314
## 224 4.13660314
## 225 -6.02339686
## 226 3.21660314
## 227 7.39660314
## 228 11.24660314
## 229 0.97160314
## 230 -5.20339686
## 231 5.53160314
## 232 -2.83339686
## 233 -12.86339686
## 234 -3.16339686
## 235 -6.15339686
## 236 -8.44339686
## 237 -3.93339686
## 238 7.72660314
## 239 -1.59339686
## 240 7.39660314
## 241 6.00660314
## 242 -8.52839686
## 243 -3.86339686
## 244 4.63660314
## 245 -2.92339686
## 246 -0.64339686
## 247 7.39660314
## 248 5.19660314
## 249 -9.76339686
## 250 -1.68839686
## 251 -13.37339686
## 252 1.53660314
## 253 3.54660314
## 254 -0.36339686
## 255 1.16160314
## 256 -5.29839686
## 257 2.96660314
## 258 9.48660314
## 259 -6.24839686
## 260 1.25660314
## 261 -5.46339686
## 262 -3.82339686
## 263 -6.34339686
## 264 6.29160314
## 265 7.39660314
## 266 11.68660314
## 267 -10.86339686
## 268 1.73160314
## 269 -0.46339686
## 270 -4.82339686
## 271 -1.29339686
## 272 3.53660314
## 273 6.38660314
## 274 -3.20839686
## 275 -3.11339686
## 276 -4.06339686
## 277 -10.04839686
## 278 -6.36339686
## 279 1.12660314
## 280 -9.10339686
## 281 -2.54339686
## 282 9.90160314
## 283 -3.01839686
## 284 1.73160314
## 285 0.53660314
## 286 -4.04339686
## 287 17.40660314
## 288 -4.44339686
## 289 6.10160314
## 290 -4.26339686
## 291 2.73660314
## 292 -1.02339686
## 293 14.87660314
## 294 -1.84339686
## 295 -3.86339686
## 296 -7.67339686
## 297 -2.96339686
## 298 -5.25339686
## 299 3.72660314
## 300 -1.78339686
## 301 -3.11339686
## 302 -8.05339686
## 303 6.84660314
## 304 2.33660314
## 305 7.33660314
## 306 2.68160314
## 307 -3.16339686
## 308 2.66660314
## 309 4.20160314
## 310 2.39660314
## 311 -4.06339686
## 312 -5.96339686
## 313 5.30660314
## 314 5.19660314
## 315 0.73660314
## 316 2.58660314
## 317 1.54160314
## 318 2.11160314
## 319 -3.01839686
## 320 6.67160314
## 321 -5.39339686
## 322 -1.02339686
## 323 0.13660314
## 324 10.28160314
## 325 -3.46339686
## 326 3.44160314
## 327 -7.45339686
## 328 5.81660314
## 329 3.13660314
## 330 6.03660314
## 331 5.72160314
## 332 -3.30339686
## 333 0.49660314
## 334 -1.87839686
## 335 5.05660314
## 336 3.83660314
## 337 -4.92339686
## 338 -3.11339686
## 339 1.63660314
## 340 -2.94339686
## 341 -3.06339686
## 342 -0.64339686
## 343 -3.11339686
## 344 6.10160314
## 345 10.80660314
## 346 -1.40339686
## 347 5.08660314
## 348 2.68160314
## 349 -0.74339686
## 350 -2.82839686
## 351 -7.48339686
## 352 -5.06339686
## 353 -2.96339686
## 354 4.58160314
## 355 7.61660314
## 356 -3.06339686
## 357 13.22660314
## 358 -0.83339686
## 359 11.24660314
## 360 -9.87339686
## 361 1.63660314
## 362 -0.16339686
## 363 -8.96339686
## 364 -4.26339686
## 365 -8.77339686
## 366 0.11660314
## 367 1.63660314
## 368 -5.67839686
## 369 1.35160314
## 370 -0.26339686
## 371 -9.57339686
## 372 -8.43339686
## 373 2.49160314
## 374 2.23660314
## 375 2.66660314
## 376 -2.35339686
## 377 -5.77339686
## 378 9.48660314
## 379 -0.54839686
## 380 0.79660314
## 381 -12.70839686
## 382 0.02160314
## 383 2.33660314
## 384 12.67660314
## 385 -8.52839686
## 386 3.73660314
## 387 8.38660314
## 388 -5.29839686
## 389 -8.05339686
## 390 -0.45339686
## 391 4.96160314
## 392 6.76660314
## 393 0.78160314
## 394 0.68660314
## 395 1.63660314
## 396 -10.80839686
## 397 3.73660314
## 398 0.35660314
## 399 -5.06339686
## 400 7.50660314
## 401 -10.06339686
## 402 16.85660314
## 403 2.30160314
## 404 1.63660314
## 405 -10.26339686
## 406 7.71660314
## 407 -6.35339686
## 408 -7.06339686
## 409 -9.54339686
## 410 -0.63339686
## 411 -13.18339686
## 412 -10.42839686
## 413 -13.46839686
## 414 -6.76339686
## 415 4.48660314
## 416 4.97660314
## 417 3.43660314
## 418 -8.06339686
## 419 8.49660314
## 420 -3.68339686
## 421 3.21660314
## 422 5.19660314
## 423 2.11160314
## 424 -0.07339686
## 425 -0.46339686
## 426 -6.35339686
## 427 -3.39839686
## 428 -1.49839686
## 429 -13.84839686
## 430 -0.26339686
## 431 2.43660314
## 432 -10.42839686
## 433 -3.76339686
## 434 -0.16339686
## 435 -2.06839686
## 436 2.44660314
## 437 1.06660314
## 438 -1.76339686
## 439 16.08660314
## 440 -1.21339686
## 441 2.01660314
## 442 2.83660314
## 443 12.34660314
## 444 5.85660314
## 445 -3.96839686
## 446 2.43660314
## 447 -1.02339686
## 448 -5.01339686
## 449 -1.06339686
## 450 7.93660314
## 451 -1.06339686
## 452 -6.53339686
## 453 -7.26339686
## 454 -0.92839686
## 455 15.86660314
## 456 6.73660314
## 457 -0.52339686
## 458 -0.16839686
## 459 8.93660314
## 460 2.33660314
## 461 5.96660314
## 462 -0.66339686
## 463 7.43160314
## 464 -4.72839686
## 465 -5.48839686
## 466 -2.28339686
## 467 -1.96339686
## 468 3.15660314
## 469 -6.34339686
## 470 -6.57339686
## 471 2.00660314
## 472 -0.54839686
## 473 -0.86339686
## 474 2.68160314
## 475 -5.56339686
## 476 -2.35339686
## 477 -2.16339686
## 478 4.96160314
## 479 6.18660314
## 480 1.89660314
## 481 10.66160314
## 482 6.84660314
## 483 0.68660314
## 484 8.83660314
## 485 3.63660314
## 486 0.40160314
## 487 -9.19339686
## 488 -1.96339686
## 489 7.39660314
## 490 0.49660314
## 491 2.23660314
## 492 -5.58339686
## 493 -5.58339686
## 494 12.73660314
## 495 -4.96339686
## 496 -2.73339686
## 497 -7.06339686
## 498 -1.96339686
## 499 -6.68339686
## 500 8.53660314
## 501 3.73660314
## 502 -4.63339686
## 503 -7.45339686
## 504 -0.41339686
## 505 -1.73339686
## 506 0.21160314
## 507 0.68660314
## 508 -6.91339686
## 509 -5.39339686
## 510 -1.96339686
## 511 1.44660314
## 512 2.99660314
## 513 -8.24339686
## 514 -0.26339686
## 515 -2.36339686
## 516 5.03660314
## 517 4.64660314
## 518 -0.16839686
## 519 0.33660314
## 520 0.21160314
## 521 -3.30339686
## 522 13.55660314
## 523 3.25160314
## 524 7.06660314
## 525 -4.59339686
## 526 3.21660314
## 527 -0.07339686
## 528 -4.86339686
## 529 8.76160314
## 530 -5.20339686
## 531 11.46660314
## 532 1.06660314
## 533 -0.96339686
## 534 5.52660314
## 535 9.81660314
## 536 -2.63839686
## 537 8.23660314
## 538 -0.46339686
## 539 -2.61339686
## 540 0.68660314
## 541 7.33660314
## 542 1.12660314
## 543 5.63660314
## 544 16.74660314
## 545 -0.45339686
## 546 -4.82339686
## 547 4.77160314
## 548 16.03660314
## 549 -2.06839686
## 550 15.53660314
## 551 0.13660314
## 552 -1.73339686
## 553 -9.26339686
## 554 1.06660314
## 555 10.66160314
## 556 -6.86339686
## 557 2.77660314
## 558 3.54660314
## 559 3.44160314
## 560 4.86660314
## 561 -10.71339686
## 562 2.01660314
## 563 -0.16339686
## 564 14.10660314
## 565 1.45660314
## 566 -0.16839686
## 567 9.90160314
## 568 -0.07339686
## 569 1.23660314
## 570 9.90160314
## 571 -1.56339686
## 572 6.62660314
## 573 12.45660314
## 574 6.19660314
## 575 3.63160314
## 576 -3.49339686
## 577 -3.82339686
## 578 7.43160314
## 579 -0.46339686
## 580 -7.19839686
## 581 -5.20339686
## 582 -0.07339686
## 583 14.76660314
## 584 -7.01339686
## 585 -9.96339686
## 586 -2.39339686
## 587 -10.42839686
## 588 -0.45339686
## 589 5.24660314
## 590 0.02660314
## 591 -1.66339686
## 592 -11.09339686
## 593 0.46660314
## 594 -8.81339686
## 595 9.59660314
## 596 3.06160314
## 597 -1.18339686
## 598 2.58660314
## 599 1.93660314
## 600 6.86160314
## 601 8.49660314
## 602 0.97160314
## 603 -5.36339686
## 604 8.38660314
## 605 -2.35339686
## 606 3.43660314
## 607 -5.48839686
## 608 -7.00839686
## 609 -3.68339686
## 610 7.13660314
## 611 -1.29339686
## 612 4.13660314
## 613 2.49160314
## 614 -11.66339686
## 615 2.33660314
## 616 5.96660314
## 617 -2.06839686
## 618 -5.06339686
## 619 2.44660314
## 620 6.43660314
## 621 0.73660314
## 622 3.43660314
## 623 -9.36339686
## 624 2.87160314
## 625 -1.87839686
## 626 -4.63339686
## 627 -1.78339686
## 628 11.79660314
## 629 7.33660314
## 630 8.28660314
## 631 5.43660314
## 632 -1.36339686
## 633 4.86660314
## 634 -7.95839686
## 635 9.03660314
## 636 7.52660314
## 637 -6.15339686
## 638 7.43160314
## 639 -4.25339686
## 640 2.99660314
## 641 11.73660314
## 642 -2.35339686
## 643 3.25160314
## 644 4.29660314
## 645 4.64660314
## 646 0.11660314
## 647 -4.44339686
## 648 -7.29339686
## 649 -2.16339686
## 650 2.30160314
## 651 12.01660314
## 652 8.93660314
## 653 0.46660314
## 654 5.63660314
## 655 4.53660314
## 656 -5.36339686
## 657 11.73660314
## 658 2.49160314
## 659 5.24660314
## 660 -1.87839686
## 661 15.86660314
## 662 -6.68339686
## 663 0.87660314
## 664 2.99660314
## 665 -7.67339686
## 666 7.39660314
## 667 -1.96339686
## 668 2.11160314
## 669 1.35160314
## 670 -0.85339686
## 671 0.90660314
## 672 0.49660314
## 673 -0.96339686
## 674 0.35660314
## 675 13.22660314
## 676 -9.28839686
## 677 10.14660314
## 678 0.68660314
## 679 5.43660314
## 680 -7.48339686
## 681 -13.26339686
## 682 -10.36339686
## 683 4.63660314
## 684 -6.34339686
## 685 -12.16339686
## 686 -4.25339686
## 687 -4.53839686
## 688 11.02660314
## 689 -6.56339686
## 690 0.46660314
## 691 -3.30339686
## 692 5.53660314
## 693 1.73160314
## 694 -7.00839686
## 695 4.13660314
## 696 9.52160314
## 697 1.63660314
## 698 5.08660314
## 699 3.06160314
## 700 8.60660314
## 701 4.20660314
## 702 14.08160314
## 703 10.80660314
## 704 -4.25339686
## 705 -1.11839686
## 706 2.23660314
## 707 7.39660314
## 708 -1.97339686
## 709 -0.16839686
## 710 -2.92339686
## 711 4.53660314
## 712 -7.12339686
## 713 0.02160314
## 714 9.80660314
## 715 -8.06339686
## 716 -1.76339686
## 717 -8.05339686
## 718 -6.34339686
## 719 6.00660314
## 720 2.77660314
## 721 9.99660314
## 722 5.93660314
## 723 6.73660314
## 724 4.73660314
## 725 -3.58839686
## 726 8.38660314
## 727 -2.25839686
## 728 -8.90839686
## 729 9.61660314
## 730 5.41660314
## 731 -6.24339686
## 732 -9.26339686
## 733 -0.56339686
## 734 -3.39839686
## 735 1.43660314
## 736 4.10660314
## 737 7.72660314
## 738 -6.96339686
## 739 1.06660314
## 740 4.83660314
## 741 -6.62839686
## 742 -1.51339686
## 743 3.44160314
## 744 -4.04339686
## 745 -4.25339686
## 746 -0.54839686
## 747 -3.66339686
## 748 -8.90839686
## 749 5.33660314
## 750 0.21160314
## 751 -4.26339686
## 752 -1.68839686
## 753 7.24160314
## 754 -7.89339686
## 755 2.96660314
## 756 -3.01839686
## 757 -7.86339686
## 758 -2.83339686
## 759 6.76660314
## 760 7.50660314
## 761 3.91660314
## 762 4.53660314
## 763 -3.56339686
## 764 -4.63339686
## 765 -5.48839686
## 766 1.16160314
## 767 1.63660314
## 768 -1.66339686
## 769 9.03660314
## 770 -11.18839686
## 771 5.43660314
## 772 -3.96339686
## 773 5.81660314
## 774 -1.78339686
## 775 3.53660314
## 776 2.66660314
## 777 1.63660314
## 778 9.14160314
## 779 3.65660314
## 780 -1.78339686
## 781 -6.26339686
## 782 10.47660314
## 783 5.30660314
## 784 -3.06339686
## 785 -1.40339686
## 786 -2.96339686
## 787 6.29160314
## 788 6.19660314
## 789 -8.14839686
## 790 -0.74339686
## 791 11.13660314
## 792 -3.06339686
## 793 -7.48339686
## 794 -9.76339686
## 795 1.25660314
## 796 -2.16339686
## 797 13.55660314
## 798 -7.76839686
## 799 2.43660314
## 800 -5.86839686
## 801 -4.48339686
## 802 5.30660314
## 803 -8.36339686
## 804 11.57660314
## 805 -4.15339686
## 806 5.15160314
## 807 10.75660314
## 808 5.91160314
## 809 -0.52339686
## 810 -4.82339686
## 811 0.13660314
## 812 12.27660314
## 813 -9.65339686
## 814 -8.14839686
## 815 3.76660314
## 816 0.79660314
## 817 -6.43839686
## 818 6.43660314
## 819 -4.53839686
## 820 4.86660314
## 821 3.03660314
## 822 -12.99339686
## 823 0.46660314
## 824 -0.85339686
## 825 -6.34339686
## 826 1.16160314
## 827 1.12660314
## 828 -2.63839686
## 829 0.11660314
## 830 -8.81339686
## 831 2.43660314
## 832 -4.82339686
## 833 -6.81839686
## 834 3.72660314
## 835 3.15660314
## 836 5.30660314
## 837 0.83660314
## 838 -2.35339686
## 839 -7.19839686
## 840 0.68660314
## 841 0.43660314
## 842 -5.96339686
## 843 2.11660314
## 844 -0.85339686
## 845 -0.16839686
## 846 1.78660314
## 847 3.53660314
## 848 19.71660314
## 849 -6.56339686
## 850 2.11160314
## 851 0.11660314
## 852 1.63660314
## 853 4.86660314
## 854 -6.91339686
## 855 -6.81839686
## 856 -1.06339686
## 857 2.44660314
## 858 -6.53339686
## 859 1.56660314
## 860 -2.56339686
## 861 16.93660314
## 862 -2.66339686
## 863 2.87160314
## 864 -10.80839686
## 865 -5.26339686
## 866 -0.76339686
## 867 6.62660314
## 868 13.03660314
## 869 -7.00839686
## 870 -6.36339686
## 871 5.53660314
## 872 -1.18339686
## 873 -5.80339686
## 874 -0.56339686
## 875 -8.81339686
## 876 -2.54339686
## 877 -3.56339686
## 878 2.77660314
## 879 -1.86339686
## 880 -1.16339686
## 881 4.13660314
## 882 -3.30339686
## 883 -8.52839686
## 884 6.38660314
## 885 -3.96839686
## 886 -1.73339686
## 887 -1.68839686
## 888 -0.64339686
## 889 8.83660314
## 890 2.96660314
## 891 -3.77839686
## 892 -1.62339686
## 893 -6.62839686
## 894 8.27660314
## 895 1.44660314
## 896 13.33660314
## 897 -10.61839686
## 898 -5.10839686
## 899 9.59660314
## 900 -8.14839686
## 901 -8.14839686
## 902 10.25660314
## 903 -3.39839686
## 904 6.18660314
## 905 4.43660314
## 906 -1.30839686
## 907 1.92160314
## 908 1.67660314
## 909 9.13660314
## 910 -6.06339686
## 911 -2.35339686
## 912 1.06660314
## 913 -3.96839686
## 914 -3.16339686
## 915 -6.05839686
## 916 3.32660314
## 917 -3.77839686
## 918 -7.76839686
## 919 -2.46339686
## 920 3.54660314
## 921 -5.66339686
## 922 2.53660314
## 923 0.33660314
## 924 5.15160314
## 925 -7.46339686
## 926 1.44660314
## 927 -7.26339686
## 928 -10.56339686
## 929 8.49660314
## 930 3.54660314
## 931 15.86660314
## 932 1.83660314
## 933 -4.86339686
## 934 4.63660314
## 935 6.51660314
## 936 -3.16339686
## 937 -0.92839686
## 938 -6.43839686
## 939 -4.48339686
## 940 -1.18339686
## 941 -7.45339686
## 942 15.42660314
## 943 9.52160314
## 944 -8.05339686
## 945 9.26660314
## 946 5.13660314
## 947 5.13660314
## 948 3.53660314
## 949 0.59160314
## 950 -0.96339686
## 951 -12.32839686
## 952 12.23660314
## 953 -2.25839686
## 954 -0.46339686
## 955 -2.82839686
## 956 8.82660314
## 957 0.13660314
## 958 -3.87339686
## 959 4.29660314
## 960 6.00660314
## 961 8.95160314
## 962 -4.76339686
## 963 4.53660314
## 964 -5.86839686
## 965 6.10160314
## 966 -3.56339686
## 967 -5.86839686
## 968 -5.29839686
## 969 -4.91839686
## 970 3.65660314
## 971 -2.50339686
## 972 -7.10339686
## 973 -10.42839686
## 974 9.83660314
## 975 4.75660314
## 976 -7.76839686
## 977 9.48660314
## 978 -1.51339686
## 979 9.33160314
## 980 -0.74339686
## 981 -5.20339686
## 982 -9.28839686
## 983 -4.76339686
## 984 -0.07339686
## 985 -0.54839686
## 986 -4.86339686
## 987 -0.54839686
## 988 -3.01839686
## 989 4.01160314
## 990 -10.14339686
## 991 -10.86339686
## 992 -2.82839686
## 993 0.93660314
## 994 -2.39339686
## 995 -10.61839686
## 996 -7.38839686
## 997 3.43660314
## 998 6.18660314
## 999 5.62660314
## 1000 -3.77839686
## 1001 -7.67339686
## 1002 2.03660314
## 1003 -4.86339686
## 1004 -1.06339686
## 1005 -11.47339686
## 1006 1.06660314
## 1007 -1.40339686
## 1008 -2.44839686
## 1009 -5.67839686
## 1010 -2.92339686
## 1011 -7.86339686
## 1012 -10.53339686
## 1013 2.66660314
## 1014 1.63660314
## 1015 -3.06339686
## 1016 -5.20339686
## 1017 -6.05839686
## 1018 3.53660314
## 1019 5.15160314
## 1020 2.01660314
## 1021 6.33660314
## 1022 0.35660314
## 1023 5.41660314
## 1024 -7.34339686
## 1025 14.65660314
## 1026 3.93660314
## 1027 -4.63339686
## 1028 -11.94839686
## 1029 0.93660314
## 1030 -13.37339686
## 1031 -7.00839686
## 1032 4.53660314
## 1033 -2.73339686
## 1034 -9.09839686
## 1035 7.71660314
## 1036 -7.66339686
## 1037 6.40660314
## 1038 -0.16839686
## 1039 -1.78339686
## 1040 -3.39839686
## 1041 -2.63839686
## 1042 -7.57839686
## 1043 0.02160314
## 1044 -4.86339686
## 1045 4.58160314
## 1046 -5.96339686
## 1047 -5.58339686
## 1048 21.91660314
## 1049 -8.14839686
## 1050 0.23660314
## 1051 6.29160314
## 1052 -4.25339686
## 1053 -0.83339686
## 1054 -0.86339686
## 1055 -9.19339686
## 1056 -3.01839686
## 1057 -1.76339686
## 1058 1.12660314
## 1059 8.82660314
## 1060 3.15660314
## 1061 1.34660314
## 1062 -2.72339686
## 1063 10.47660314
## 1064 -2.06839686
## 1065 -5.06339686
## 1066 -5.36339686
## 1067 6.62660314
## 1068 11.99160314
## 1069 -9.00339686
## 1070 1.23660314
## 1071 6.40660314
## 1072 0.78160314
## 1073 0.59160314
## 1074 -1.78339686
## 1075 -12.32839686
## 1076 -1.07339686
## 1077 1.33660314
## 1078 -4.63339686
## 1079 1.01660314
## 1080 2.99660314
## 1081 -8.88339686
## 1082 -2.82839686
## 1083 -10.71339686
## 1084 0.83660314
## 1085 -0.16839686
## 1086 -12.36339686
## 1087 -1.68839686
## 1088 0.87660314
## 1089 17.07660314
## 1090 -8.56339686
## 1091 5.52660314
## 1092 -0.83339686
## 1093 2.03660314
## 1094 -0.26339686
## 1095 3.03660314
## 1096 0.68660314
## 1097 4.29660314
## 1098 3.10660314
## 1099 0.21160314
## 1100 3.32660314
## 1101 -11.56839686
## 1102 -2.06339686
## 1103 8.27660314
## 1104 5.41660314
## 1105 -0.86339686
## 1106 0.57660314
## 1107 -0.73839686
## 1108 -4.44339686
## 1109 -0.66339686
## 1110 -10.31339686
## 1111 1.63660314
## 1112 7.72660314
## 1113 -4.81339686
## 1114 -4.34839686
## 1115 -6.15339686
## 1116 2.00660314
## 1117 -1.02339686
## 1118 2.66660314
## 1119 5.08660314
## 1120 -10.71339686
## 1121 0.73660314
## 1122 7.50660314
## 1123 6.19660314
## 1124 1.73160314
## 1125 12.08660314
## 1126 -5.58339686
## 1127 -0.76339686
## 1128 5.19660314
## 1129 2.13660314
## 1130 -12.06339686
## 1131 -6.79339686
## 1132 15.23660314
## 1133 9.61660314
## 1134 -12.32839686
## 1135 3.15660314
## 1136 -2.54339686
## 1137 -5.66339686
## 1138 -8.43339686
## 1139 -0.41339686
## 1140 1.82660314
## 1141 6.40660314
## 1142 1.93660314
## 1143 -5.80339686
## 1144 1.67660314
## 1145 1.63660314
## 1146 2.11160314
## 1147 2.13660314
## 1148 1.25660314
## 1149 -9.16339686
## 1150 3.43660314
## 1151 -0.35839686
## 1152 5.81660314
## 1153 1.89660314
## 1154 5.15160314
## 1155 -2.73339686
## 1156 -8.52839686
## 1157 14.21660314
## 1158 -7.48339686
## 1159 -0.07339686
## 1160 10.43660314
## 1161 3.91660314
## 1162 11.46660314
## 1163 8.16660314
## 1164 -2.44839686
## 1165 -2.35339686
## 1166 -4.53839686
## 1167 9.70660314
## 1168 -6.06339686
## 1169 4.53660314
## 1170 3.44160314
## 1171 -3.30339686
## 1172 -3.96339686
## 1173 11.24660314
## 1174 -1.40339686
## 1175 1.44660314
## 1176 -3.56339686
## 1177 -6.53339686
## 1178 -3.26339686
## 1179 4.20160314
## 1180 -0.85339686
## 1181 10.66160314
## 1182 -0.73839686
## 1183 -0.36339686
## 1184 -3.30339686
## 1185 -2.17339686
## 1186 -7.10339686
## 1187 4.96160314
## 1188 2.01660314
## 1189 -5.39339686
## 1190 -2.66339686
## 1191 2.11160314
## 1192 -8.90839686
## 1193 1.73160314
## 1194 5.91160314
## 1195 -8.90839686
## 1196 -2.73339686
## 1197 -0.64339686
## 1198 2.88660314
## 1199 -1.30839686
## 1200 -4.86339686
## 1201 -6.34339686
## 1202 9.71160314
## 1203 1.44660314
## 1204 1.63660314
## 1205 -3.38339686
## 1206 -12.80339686
## 1207 4.13660314
## 1208 2.73660314
## 1209 -5.10839686
## 1210 6.43660314
## 1211 0.21160314
## 1212 3.43660314
## 1213 -9.19339686
## 1214 2.63660314
## 1215 0.59160314
## 1216 8.47660314
## 1217 -5.58339686
## 1218 6.62660314
## 1219 3.93660314
## 1220 -0.45339686
## 1221 -8.71839686
## 1222 -5.69339686
## 1223 -5.36339686
## 1224 -6.24339686
## 1225 -6.72339686
## 1226 9.15660314
## 1227 -13.84839686
## 1228 6.51660314
## 1229 3.76660314
## 1230 -0.35839686
## 1231 3.82160314
## 1232 -8.86339686
## 1233 -6.05839686
## 1234 -7.36339686
## 1235 -2.83339686
## 1236 0.40160314
## 1237 -9.00339686
## 1238 -2.44839686
## 1239 -7.95839686
## 1240 11.46660314
## 1241 11.13660314
## 1242 6.29660314
## 1243 -9.38339686
## 1244 2.44660314
## 1245 2.66660314
## 1246 -6.36339686
## 1247 -4.96339686
## 1248 -1.26339686
## 1249 9.15660314
## 1250 2.96660314
## 1251 -0.83339686
## 1252 -10.86339686
## 1253 -3.36339686
## 1254 -1.36339686
## 1255 -2.94339686
## 1256 7.23660314
## 1257 5.72160314
## 1258 -3.01839686
## 1259 7.05160314
## 1260 -7.48339686
## 1261 -10.14339686
## 1262 6.43660314
## 1263 -2.61339686
## 1264 -0.76339686
## 1265 2.68160314
## 1266 -6.90339686
## 1267 -0.16339686
## 1268 0.40160314
## 1269 2.63660314
## 1270 -3.16339686
## 1271 3.25160314
## 1272 3.82160314
## 1273 -5.14339686
## 1274 -3.05339686
## 1275 -3.60339686
## 1276 -6.96339686
## 1277 -0.26339686
## 1278 -0.92839686
## 1279 -0.73839686
## 1280 -3.87339686
## 1281 2.66660314
## 1282 -3.01839686
## 1283 -9.00339686
## 1284 -0.63339686
## 1285 5.63660314
## 1286 -6.34339686
## 1287 -13.37339686
## 1288 -4.76339686
## 1289 8.73660314
## 1290 3.65660314
## 1291 -10.71339686
## 1292 4.23660314
## 1293 -7.45339686
## 1294 -4.91839686
## 1295 -5.48839686
## 1296 -8.66339686
## 1297 -4.53839686
## 1298 -4.15339686
## 1299 -3.20839686
## 1300 -4.91839686
## 1301 -0.30339686
## 1302 0.21160314
## 1303 -9.86339686
## 1304 -2.86339686
## 1305 -6.05839686
## 1306 -2.94339686
## 1307 -8.81339686
## 1308 -2.54339686
## 1309 -0.46339686
## 1310 1.53660314
## 1311 -4.34839686
## 1312 -3.96839686
## 1313 12.23660314
## 1314 4.03660314
## 1315 -7.00839686
## 1316 -2.35339686
## 1317 -10.06339686
## 1318 22.46660314
## 1319 9.04660314
## 1320 -4.34839686
## 1321 0.40160314
## 1322 -3.96839686
## 1323 8.16660314
## 1324 9.70660314
## 1325 -4.72839686
## 1326 2.87160314
## 1327 2.20660314
## 1328 -0.63339686
## 1329 -6.43839686
## 1330 7.93660314
## 1331 -4.92339686
## 1332 2.73660314
## 1333 14.03660314
## 1334 0.30660314
## 1335 1.25660314
## 1336 6.18660314
## 1337 -4.86339686
## 1338 -1.59339686</code></pre>
<pre class="r"><code>library(glmnet)
y&lt;-as.matrix(insurance$smoker) 
x&lt;-model.matrix(smoker~.,data=insurance)[,-1] 
head(x)</code></pre>
<pre><code>## age sexmale bmi children regionnorthwest regionsoutheast
regionsouthwest charges bmi_c
## 1 19 0 27.900 0 0 0 1 16884.924 -2.763397
## 2 18 1 33.770 1 0 1 0 1725.552 3.106603
## 3 28 1 33.000 3 0 1 0 4449.462 2.336603
## 4 33 1 22.705 0 1 0 0 21984.471 -7.958397
## 5 32 1 28.880 0 1 0 0 3866.855 -1.783397
## 6 31 0 25.740 0 0 1 0 3756.622 -4.923397</code></pre>
<pre class="r"><code>cv&lt;-cv.glmnet(x,y,family=&quot;binomial&quot;)
lasso&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 10 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                            s0
## (Intercept)      1.0257377417
## age             -0.0520566117
## sexmale          .           
## bmi             -0.1629551289
## children         .           
## regionnorthwest  .           
## regionsoutheast  .           
## regionsouthwest  .           
## charges          0.0002518722
## bmi_c           -0.0032424157</code></pre>
<pre class="r"><code>lasso_dat &lt;- insurance %&gt;% mutate(smoker= ifelse(smoker==&quot;yes&quot;, 1, 0)) 
set.seed(1234)
k=10

data1 &lt;- lasso_dat %&gt;% sample_frac 
folds &lt;- ntile(1:nrow(data),n=10) 

diags1&lt;-NULL
for(i in 1:k){
  train &lt;- data1[folds!=i,] 
  test &lt;- data1[folds==i,] 
  truth &lt;- test$smoker
  
  fit1 &lt;- glm(smoker~., 
             data=data1, family=&quot;binomial&quot;)
  probs1 &lt;- predict(fit1, newdata=test, type=&quot;response&quot;)
  
  diags&lt;-rbind(diags1,class_diag(probs1,truth))
}

diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##         acc sens      spec       ppv       auc
## 1 0.9774436 0.96 0.9814815 0.9230769 0.9907407</code></pre>
</div>
<div id="the-variables-that-are-retained-are-age-and-bmi.-the-reason-why-these-variables-are-the-ones-that-are-in-the-lasso-output-is-because-they-are-very-significant-and-are-tied-to-whether-or-not-an-individual-is-a-smoker.-the-out-of-sample-auc-here-is-0.991-which-is-a-little-higher-than-the-in-sample-auc-0.987." class="section level2">
<h2>The variables that are retained are age and bmi. The reason why these variables are the ones that are in the LASSO output is because they are very significant and are tied to whether or not an individual is a smoker. The out of sample AUC here is 0.991, which is a little higher than the in-sample AUC (0.987).</h2>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
